// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/test/db-setup.ts

type TableName = "users" | "daily_reports" | "report_send_history" | "audit_events";

interface TableRow {
  [key: string]: unknown;
}

interface TableOperations {
  del(): Promise<void>;
  insert(row: TableRow): Promise<void>;
  where(conditions: Record<string, unknown>): Promise<TableRow[]>;
}

interface TestDatabase {
  (tableName: TableName): TableOperations;
}

const createTestDatabase = async (): Promise<TestDatabase> => {
  const tables: Record<TableName, TableRow[]> = {
    users: [],
    daily_reports: [],
    report_send_history: [],
    audit_events: [],
  };

  const testDb: TestDatabase = (tableName: TableName): TableOperations => {
    return {
      del: async () => {
        tables[tableName] = [];
      },
      insert: async (row: TableRow) => {
        tables[tableName].push(row);
      },
      where: async (conditions: Record<string, unknown>) => {
        return tables[tableName].filter((row) => {
          return Object.entries(conditions).every(([key, value]) => {
            return row[key] === value;
          });
        });
      },
    };
  };

  return testDb;
};

const cleanupTestDatabase = async (testDb: TestDatabase): Promise<void> => {
  const tableNames: TableName[] = [
    "users",
    "daily_reports",
    "report_send_history",
    "audit_events",
  ];

  for (const tableName of tableNames) {
    await testDb(tableName).del();
  }
};

export { createTestDatabase, cleanupTestDatabase };
