// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/test/db-setup.ts

type TableName = "users" | "daily_reports" | "report_send_history" | "audit_events";

interface TableRow {
  [key: string]: unknown;
}

interface TableOperations {
  del(): Promise<number>;
  insert(row: TableRow | TableRow[]): Promise<void>;
  where(conditions: Record<string, unknown>): Promise<TableRow[]>;
}

interface TestDatabase {
  (tableName: TableName): TableOperations;
}

const memoryStore: Record<TableName, TableRow[]> = {
  users: [],
  daily_reports: [],
  report_send_history: [],
  audit_events: [],
};

function createTableOperations(tableName: TableName): TableOperations {
  return {
    async del(): Promise<number> {
      const count = memoryStore[tableName].length;
      memoryStore[tableName] = [];
      return count;
    },

    async insert(row: TableRow | TableRow[]): Promise<void> {
      const rows = Array.isArray(row) ? row : [row];
      memoryStore[tableName].push(...rows);
    },

    async where(conditions: Record<string, unknown>): Promise<TableRow[]> {
      return memoryStore[tableName].filter((row) => {
        return Object.entries(conditions).every(([key, value]) => {
          return row[key] === value;
        });
      });
    },
  };
}

export async function createTestDatabase(): Promise<TestDatabase> {
  memoryStore.users = [];
  memoryStore.daily_reports = [];
  memoryStore.report_send_history = [];
  memoryStore.audit_events = [];

  return (tableName: TableName): TableOperations => {
    return createTableOperations(tableName);
  };
}

export async function cleanupTestDatabase(db: TestDatabase): Promise<void> {
  await db("users").del();
  await db("daily_reports").del();
  await db("report_send_history").del();
  await db("audit_events").del();
}
