// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/test/db-setup.ts

type TableName = "users" | "daily_reports" | "report_send_history" | "audit_events";

interface TableData {
  users: Array<{
    user_id: string;
    user_name: string;
    department: string;
    role: string;
  }>;
  daily_reports: Array<{
    report_id: string;
    user_id: string;
    report_date: string;
    yesterday_achievement: string;
    today_plan: string;
    issues: string;
    created_at: Date;
  }>;
  report_send_history: Array<{
    history_id: string;
    user_id: string;
    report_date: string;
    sent_at: Date;
    status: string;
  }>;
  audit_events: Array<{
    event_type: string;
    target_role: string;
    unsubmitted_count: number;
    timestamp: Date;
    [key: string]: unknown;
  }>;
}

interface TestDatabase {
  (tableName: TableName): {
    del: () => Promise<void>;
    insert: (data: unknown) => Promise<void>;
    where: (conditions: Record<string, unknown>) => Promise<unknown[]>;
  };
}

const inMemoryStore: Map<TableName, unknown[]> = new Map([
  ["users", []],
  ["daily_reports", []],
  ["report_send_history", []],
  ["audit_events", []],
]);

export async function createTestDatabase(): Promise<TestDatabase> {
  inMemoryStore.clear();
  inMemoryStore.set("users", []);
  inMemoryStore.set("daily_reports", []);
  inMemoryStore.set("report_send_history", []);
  inMemoryStore.set("audit_events", []);

  return (tableName: TableName) => ({
    del: async () => {
      inMemoryStore.set(tableName, []);
    },
    insert: async (data: unknown) => {
      const table = inMemoryStore.get(tableName) || [];
      table.push(data);
      inMemoryStore.set(tableName, table);
    },
    where: async (conditions: Record<string, unknown>) => {
      const table = inMemoryStore.get(tableName) || [];
      return table.filter((row: unknown) => {
        if (typeof row !== "object" || row === null) return false;
        const rowObj = row as Record<string, unknown>;
        return Object.entries(conditions).every(
          ([key, value]) => rowObj[key] === value
        );
      });
    },
  });
}

export async function cleanupTestDatabase(db: TestDatabase): Promise<void> {
  const tableNames: TableName[] = [
    "users",
    "daily_reports",
    "report_send_history",
    "audit_events",
  ];
  for (const tableName of tableNames) {
    await db(tableName).del();
  }
  inMemoryStore.clear();
}
