// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/log-service.ts

export async function logError(message: string): Promise<void> {
  // メモリ内ログストレージ
  if (!globalThis.__logErrorStore) {
    (globalThis as any).__logErrorStore = [];
  }
  (globalThis as any).__logErrorStore.push({
    message,
    timestamp: new Date(),
  });
}
