// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/log-service.ts

export async function logError(message: string): Promise<void> {
  // メモリ内ログストレージ
  if (!globalThis.__logErrorStore) {
    globalThis.__logErrorStore = [];
  }
  globalThis.__logErrorStore.push({
    timestamp: new Date(),
    message,
  });
}

declare global {
  var __logErrorStore: Array<{ timestamp: Date; message: string }> | undefined;
}
