// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/log-service.ts

export async function logError(message: string): Promise<void> {
  // メモリ内ログストレージ
  if (!globalThis.__logErrorHistory) {
    (globalThis as any).__logErrorHistory = [];
  }
  (globalThis as any).__logErrorHistory.push({
    timestamp: new Date(),
    message,
  });
}
