// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/logger.ts

type LogLevel = 'warn' | 'info';

interface LogEntry {
  level: LogLevel;
  message: string;
  timestamp: string;
}

const logs: LogEntry[] = [];

function formatTimestamp(): string {
  return new Date().toISOString();
}

export function warn(message: string): void {
  const entry: LogEntry = {
    level: 'warn',
    message,
    timestamp: formatTimestamp(),
  };
  logs.push(entry);
  console.warn(`[${entry.timestamp}] WARN: ${message}`);
}

export function info(message: string): void {
  const entry: LogEntry = {
    level: 'info',
    message,
    timestamp: formatTimestamp(),
  };
  logs.push(entry);
  console.info(`[${entry.timestamp}] INFO: ${message}`);
}
