// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/logger.ts

type LogLevel = 'warn' | 'info';

interface LogEntry {
  level: LogLevel;
  message: string;
  timestamp: string;
}

const logs: LogEntry[] = [];

function warn(message: string): void {
  const entry: LogEntry = {
    level: 'warn',
    message,
    timestamp: new Date().toISOString(),
  };
  logs.push(entry);
}

function info(message: string): void {
  const entry: LogEntry = {
    level: 'info',
    message,
    timestamp: new Date().toISOString(),
  };
  logs.push(entry);
}

export { warn, info };
