// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail-service.ts

export interface SendConfirmationEmailRequest {
  manager_email: string | null;
  unsubmitted_members: Array<{
    user_id: string;
    user_name: string;
    email: string;
  }>;
  scheduled_meeting_time: Date;
  current_timestamp: Date;
}

export interface SendConfirmationEmailResponse {
  success: boolean;
  error?: string;
  status?: string;
  message_id?: string;
}

export interface ReportData {
  user_id: string;
  report_date: string;
  yesterday_achievement: string;
  today_plan: string;
  issue_held: string;
  submitted_at: string;
}

export interface SendConfirmationEmailParams {
  report_data?: ReportData;
  manager_email?: string;
  engineer_email?: string;
  [key: string]: any;
}

export async function sendConfirmationEmail(
  params: SendConfirmationEmailRequest | SendConfirmationEmailParams
): Promise<SendConfirmationEmailResponse> {
  const request = params as SendConfirmationEmailRequest;

  if (request.manager_email === null) {
    return {
      success: false,
      error: 'TypeError: 部長メールアドレスがnull',
    };
  }

  if (request.manager_email === undefined) {
    return {
      success: false,
      error: 'TypeError: 部長メールアドレスがnull',
    };
  }

  return {
    success: true,
    status: 'sent',
    message_id: `msg_${Date.now()}`,
  };
}
