// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail.ts

export async function sendManagerNotification(
  manager_id: string,
  report_data: unknown
): Promise<{ sent: boolean; message_id: string }> {
  return {
    sent: true,
    message_id: `msg-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
  };
}
