// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail-stub.ts

// src/services/mail-stub.ts

interface MailServiceCallRecord {
  timestamp: Date;
  managerUserId: string;
  listId: string;
  memberCount: number;
  success: boolean;
  error?: string;
}

interface StubMailService {
  sendNotificationEmail(
    managerUserId: string,
    listId: string,
    memberCount: number
  ): Promise<void>;
  clearCallHistory(): void;
  getCallHistory(): MailServiceCallRecord[];
}

let callHistory: MailServiceCallRecord[] = [];

export function getStubMailService(): StubMailService {
  return {
    async sendNotificationEmail(
      managerUserId: string,
      listId: string,
      memberCount: number
    ): Promise<void> {
      const record: MailServiceCallRecord = {
        timestamp: new Date(),
        managerUserId,
        listId,
        memberCount,
        success: true,
      };

      try {
        // スタブ実装: メール送信をシミュレート
        // テストで必要に応じてモック化される前提
        callHistory.push(record);
      } catch (error) {
        record.success = false;
        record.error = error instanceof Error ? error.message : String(error);
        callHistory.push(record);
        throw error;
      }
    },

    clearCallHistory(): void {
      callHistory = [];
    },

    getCallHistory(): MailServiceCallRecord[] {
      return [...callHistory];
    },
  };
}
