// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail-service.ts

export interface SendConfirmationEmailRequest {
  manager_email: string | null;
  unsubmitted_members?: Array<{
    user_id: string;
    user_name: string;
    email: string;
  }>;
  reports?: Array<{
    user_id: string;
    report_date: string;
    yesterday_achievement: string;
    today_plan: string;
    issue_held: string;
    submitted_at: string;
  }>;
  report_data?: {
    user_id: string;
    report_date: string;
    yesterday_achievement: string;
    today_plan: string;
    issue_held: string;
    submitted_at: string;
  };
  scheduled_meeting_time?: Date;
  current_timestamp?: Date;
  manager_email_param?: string;
  engineer_email?: string;
}

export interface SendConfirmationEmailResponse {
  success: boolean;
  error?: string;
  status?: string;
  message_id?: string;
}

const confirmationEmailHistory: Array<{
  timestamp: Date;
  manager_email: string | null;
  status: string;
  error?: string;
}> = [];

export async function sendConfirmationEmail(
  request: SendConfirmationEmailRequest
): Promise<SendConfirmationEmailResponse> {
  if (request.manager_email === null) {
    const errorMessage = 'TypeError: 部長メールアドレスがnull';
    confirmationEmailHistory.push({
      timestamp: new Date(),
      manager_email: null,
      status: 'failed',
      error: errorMessage,
    });
    return {
      success: false,
      error: errorMessage,
    };
  }

  confirmationEmailHistory.push({
    timestamp: new Date(),
    manager_email: request.manager_email,
    status: 'sent',
  });

  return {
    success: true,
    status: 'sent',
    message_id: `msg_${Date.now()}`,
  };
}
