// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail-stub.ts

interface MailServiceCallRecord {
  to: string;
  subject: string;
  body: string;
  timestamp: Date;
}

interface StubMailService {
  sendMail(to: string, subject: string, body: string): Promise<void>;
  clearCallHistory(): void;
  getCallHistory(): MailServiceCallRecord[];
}

export function getStubMailService(): StubMailService {
  const callHistory: MailServiceCallRecord[] = [];

  return {
    async sendMail(to: string, subject: string, body: string): Promise<void> {
      callHistory.push({
        to,
        subject,
        body,
        timestamp: new Date(),
      });
    },

    clearCallHistory(): void {
      callHistory.length = 0;
    },

    getCallHistory(): MailServiceCallRecord[] {
      return [...callHistory];
    },
  };
}
