// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/services/mail-stub.ts

// src/services/mail-stub.ts

interface MailCallRecord {
  to: string;
  subject: string;
  body: string;
  timestamp: Date;
}

interface StubMailService {
  sendMail(to: string, subject: string, body: string): Promise<void>;
  getCallHistory(): MailCallRecord[];
  clearCallHistory(): void;
}

const mailCallHistory: MailCallRecord[] = [];

export function getStubMailService(): StubMailService {
  return {
    async sendMail(to: string, subject: string, body: string): Promise<void> {
      mailCallHistory.push({
        to,
        subject,
        body,
        timestamp: new Date(),
      });
    },

    getCallHistory(): MailCallRecord[] {
      return [...mailCallHistory];
    },

    clearCallHistory(): void {
      mailCallHistory.length = 0;
    },
  };
}
