// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/orchestrator.ts
export { runTx4Imp1Agent } from "../../logic/it-1";
export type { Tx4Imp1AiClient } from "../../logic/it-1";
