// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/types.ts
export type { Tx4Imp1AiClientRequest, Tx4Imp1AiClientResponse, Tx4Imp1AiClient } from "../../logic/it-1";
