// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportContent: string;
  extractedIssues: Array<{
    id: string;
    title: string;
    description: string;
    category: string;
  }>;
  teamMembers: Array<{
    id: string;
    name: string;
    department: string;
  }>;
  priorityFramework: {
    criteria: string[];
    levels: string[];
  };
}

interface Action03PromptOutput {
  version: string;
  systemPrompt: string;
  userPrompt: string;
  context: {
    taskDescription: string;
    objectives: string[];
    constraints: string[];
  };
}

function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const systemPrompt = `You are an AI agent responsible for extracting and prioritizing issues from daily reports in the morning meeting preparation system.

Your role is to:
1. Analyze the provided report content and extracted issues
2. Apply the priority framework to classify and rank issues
3. Identify bottlenecks and dependencies between issues
4. Provide clear prioritization recommendations

You must follow the priority framework strictly and provide structured output that can be used by the department head for decision-making.`;

  const issuesContext = input.extractedIssues
    .map(
      (issue) =>
        `- [${issue.id}] ${issue.title} (${issue.category}): ${issue.description}`
    )
    .join("\n");

  const teamContext = input.teamMembers
    .map((member) => `- ${member.name} (${member.department})`)
    .join("\n");

  const userPrompt = `Based on the following report content and extracted issues, prioritize them using the provided framework.

Report Content:
${input.reportContent}

Extracted Issues:
${issuesContext}

Team Members:
${teamContext}

Priority Framework:
Criteria: ${input.priorityFramework.criteria.join(", ")}
Priority Levels: ${input.priorityFramework.levels.join(" > ")}

Please provide:
1. Prioritized issue list with justification
2. Identified bottlenecks and dependencies
3. Recommended actions for each priority level
4. Risk assessment for high-priority issues`;

  return {
    version: ACTION_03_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    context: {
      taskDescription:
        "Extract and prioritize issues from daily reports for morning meeting preparation",
      objectives: [
        "Classify issues by priority level",
        "Identify dependencies and bottlenecks",
        "Provide actionable recommendations",
        "Assess risks for critical issues",
      ],
      constraints: [
        "Must follow the provided priority framework",
        "Must consider team capacity and dependencies",
        "Must provide clear justification for prioritization",
        "Must identify escalation-worthy issues",
      ],
    },
  };
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
