// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportContent: string;
  engineerName: string;
  submissionDate: string;
  validationRules?: {
    minLength?: number;
    maxLength?: number;
    requiredFields?: string[];
  };
}

export interface Action02PromptOutput {
  isValid: boolean;
  validationErrors: string[];
  sanitizedContent: string;
  warnings: string[];
}

export function buildAction02Prompt(input: Action02PromptInput): string {
  const {
    reportContent,
    engineerName,
    submissionDate,
    validationRules = {
      minLength: 10,
      maxLength: 5000,
      requiredFields: ["yesterday", "today", "issues"],
    },
  } = input;

  const requiredFieldsText =
    validationRules.requiredFields?.join(", ") || "yesterday, today, issues";
  const minLength = validationRules.minLength || 10;
  const maxLength = validationRules.maxLength || 5000;

  return `You are a validation agent for the morning report management system.

Your task is to validate the daily report submission from engineer: ${engineerName}
Submission date: ${submissionDate}

Report content to validate:
---
${reportContent}
---

Validation rules:
1. Content length must be between ${minLength} and ${maxLength} characters
2. Must contain all required sections: ${requiredFieldsText}
3. Content must be professional and appropriate
4. No sensitive information should be exposed
5. Report should be coherent and understandable

Please perform the following validations:
1. Check if all required fields are present
2. Verify content length is within acceptable range
3. Identify any inappropriate or sensitive content
4. Check for coherence and clarity
5. Identify any warnings or concerns

Respond with:
- A list of validation errors (if any)
- A list of warnings (if any)
- The sanitized content (with any sensitive information removed)
- Overall validation status (valid/invalid)

Format your response as JSON with the following structure:
{
  "isValid": boolean,
  "validationErrors": string[],
  "sanitizedContent": string,
  "warnings": string[]
}`;
}
