// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptContext {
  reportCollectionStatus: {
    totalEngineers: number;
    submittedCount: number;
    pendingEngineers: string[];
    overdueEngineers: string[];
  };
  extractedIssues: Array<{
    id: string;
    title: string;
    description: string;
    reportedBy: string;
    severity: "low" | "medium" | "high" | "critical";
  }>;
  priorityClassification: Array<{
    issueId: string;
    priority: number;
    category: string;
    reasoning: string;
  }>;
  reportingDeadline: string;
  currentTimestamp: string;
}

export interface Action04PromptResult {
  action: "escalate" | "proceed" | "hold";
  reasoning: string;
  nextSteps: string[];
  requiresHumanReview: boolean;
  reviewReason?: string;
}

export function buildAction04Prompt(context: Action04PromptContext): string {
  const submissionRate = (
    (context.reportCollectionStatus.submittedCount /
      context.reportCollectionStatus.totalEngineers) *
    100
  ).toFixed(1);

  const pendingList =
    context.reportCollectionStatus.pendingEngineers.length > 0
      ? context.reportCollectionStatus.pendingEngineers.join(", ")
      : "なし";

  const overdueList =
    context.reportCollectionStatus.overdueEngineers.length > 0
      ? context.reportCollectionStatus.overdueEngineers.join(", ")
      : "なし";

  const issuesSection =
    context.extractedIssues.length > 0
      ? context.extractedIssues
          .map(
            (issue) =>
              `- [${issue.severity.toUpperCase()}] ${issue.title} (報告者: ${issue.reportedBy})\n  ${issue.description}`
          )
          .join("\n")
      : "抽出された課題なし";

  const prioritySection =
    context.priorityClassification.length > 0
      ? context.priorityClassification
          .map(
            (p) =>
              `- 優先度 ${p.priority}: ${p.category} (理由: ${p.reasoning})`
          )
          .join("\n")
      : "優先度分類なし";

  return `# 日報収集から課題抽出・優先度判定までの自動実行 - Action 04

## 現在の状況
- 報告期限: ${context.reportingDeadline}
- 現在時刻: ${context.currentTimestamp}
- 提出率: ${submissionRate}% (${context.reportCollectionStatus.submittedCount}/${context.reportCollectionStatus.totalEngineers})
- 未提出者: ${pendingList}
- 期限超過者: ${overdueList}

## 抽出された課題・ボトルネック
${issuesSection}

## 課題の優先度分類
${prioritySection}

## 判定タスク
以下の条件に基づいて、次のアクションを判定してください:

1. **提出率が100%未満の場合**: 未提出者への再催促が必要か判定
2. **期限超過者がいる場合**: エスカレーション対象か判定
3. **抽出課題の優先度判定**: 
   - Critical: 即座に対応が必要な課題
   - High: 本日中に対応すべき課題
   - Medium: 今週中に対応すべき課題
   - Low: 優先度が低い課題
4. **人的レビュー要否**: 以下の場合は人的レビューが必須
   - 複数の Critical 課題が同時に検出された
   - 通常と異なるパターンの課題が検出された
   - 優先度判定が困難な同等レベルの課題がある
   - 重大なリスク課題が検出された

## 出力形式
JSON形式で以下を返してください:
{
  "action": "escalate" | "proceed" | "hold",
  "reasoning": "判定理由を簡潔に説明",
  "nextSteps": ["次のステップ1", "次のステップ2", ...],
  "requiresHumanReview": true | false,
  "reviewReason": "人的レビューが必要な場合のみ記入"
}`;
}
