// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-05.ts

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Context {
  confirmationEmailContent: string;
  reportSubmissionDeadline: string;
  currentTimestamp: string;
  previousEscalationHistory: Array<{
    employeeId: string;
    escalationCount: number;
    lastEscalationTime: string;
  }>;
}

export interface ExtractedIssue {
  id: string;
  title: string;
  description: string;
  affectedEmployees: string[];
  severity: "critical" | "high" | "medium" | "low";
  category: string;
}

export interface PrioritizedIssue extends ExtractedIssue {
  priority: number;
  reasoning: string;
  recommendedAction: string;
}

export interface Action05Result {
  extractedIssues: ExtractedIssue[];
  prioritizedIssues: PrioritizedIssue[];
  overallProgressSummary: string;
  bottlenecks: string[];
  riskFactors: string[];
  escalationRecommendations: Array<{
    employeeId: string;
    reason: string;
    suggestedAction: string;
  }>;
}

export function buildAction05Prompt(context: Action05Context): string {
  const {
    confirmationEmailContent,
    reportSubmissionDeadline,
    currentTimestamp,
    previousEscalationHistory,
  } = context;

  const escalationHistoryText =
    previousEscalationHistory.length > 0
      ? previousEscalationHistory
          .map(
            (h) =>
              `- Employee ${h.employeeId}: ${h.escalationCount} escalations (last: ${h.lastEscalationTime})`
          )
          .join("\n")
      : "No previous escalation history";

  return `You are an AI agent responsible for analyzing confirmation emails containing daily reports and extracting critical information for morning meeting preparation.

## Task: Extract Issues, Analyze Progress, and Prioritize Concerns

### Input Data:
**Confirmation Email Content:**
${confirmationEmailContent}

**Report Submission Deadline:** ${reportSubmissionDeadline}
**Current Timestamp:** ${currentTimestamp}

**Previous Escalation History:**
${escalationHistoryText}

### Your Responsibilities:

1. **Extract Issues and Bottlenecks**
   - Identify all mentioned problems, blockers, and concerns from the report content
   - Categorize each issue by type (technical, resource, process, external dependency, etc.)
   - Determine affected team members and projects
   - Assess severity based on impact and urgency

2. **Analyze Overall Progress**
   - Summarize the overall team progress status
   - Identify trends and patterns across multiple reports
   - Highlight any anomalies or unexpected situations

3. **Prioritize Issues**
   - Assign priority scores (1-10, where 10 is highest priority)
   - Consider business impact, urgency, and dependencies
   - Provide reasoning for each priority assignment
   - Recommend specific actions for high-priority issues

4. **Identify Risk Factors**
   - Detect potential risks that could impact project delivery
   - Flag repeated issues from the same team members
   - Identify resource constraints or capacity issues

5. **Escalation Assessment**
   - Review previous escalation history
   - Determine if additional escalations are needed
   - Recommend escalation actions with justification

### Output Format:
Return a JSON object with the following structure:
{
  "extractedIssues": [
    {
      "id": "ISSUE_001",
      "title": "Issue Title",
      "description": "Detailed description",
      "affectedEmployees": ["emp_id_1", "emp_id_2"],
      "severity": "high",
      "category": "technical"
    }
  ],
  "prioritizedIssues": [
    {
      "id": "ISSUE_001",
      "title": "Issue Title",
      "description": "Detailed description",
      "affectedEmployees": ["emp_id_1"],
      "severity": "high",
      "category": "technical",
      "priority": 9,
      "reasoning": "Why this priority was assigned",
      "recommendedAction": "Specific action to address this issue"
    }
  ],
  "overallProgressSummary": "Summary of team progress status",
  "bottlenecks": ["Bottleneck 1", "Bottleneck 2"],
  "riskFactors": ["Risk 1", "Risk 2"],
  "escalationRecommendations": [
    {
      "employeeId": "emp_id",
      "reason": "Why escalation is needed",
      "suggestedAction": "Recommended escalation action"
    }
  ]
}

### Guidelines:
- Be thorough but concise in analysis
- Focus on actionable insights for the morning meeting
- Consider context from previous escalation history
- Ensure all identified issues have clear priority and recommended actions
- Flag any critical or time-sensitive matters for immediate attention`;
}
