// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-06.ts

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06Context {
  extractedIssues: Array<{
    id: string;
    title: string;
    description: string;
    reportedBy: string;
    reportedDate: string;
  }>;
  priorityClassifications: Array<{
    issueId: string;
    priority: "critical" | "high" | "medium" | "low";
    reasoning: string;
  }>;
  reportSummary: {
    totalReports: number;
    submittedReports: number;
    pendingReports: number;
    overallProgress: string;
  };
}

export interface Action06PromptInput {
  context: Action06Context;
  departmentHeadEmail: string;
  reportGenerationTime: string;
}

export interface Action06PromptOutput {
  reportContent: string;
  priorityListContent: string;
  escalationFlags: Array<{
    type: "unusual_issue" | "conflicting_priority" | "critical_risk" | "incomplete_data";
    description: string;
    requiresHumanReview: boolean;
  }>;
}

export function buildAction06Prompt(input: Action06PromptInput): string {
  const {
    context,
    departmentHeadEmail,
    reportGenerationTime,
  } = input;

  const issuesSection = context.extractedIssues
    .map((issue) => {
      const classification = context.priorityClassifications.find(
        (pc) => pc.issueId === issue.id
      );
      return `
Issue ID: ${issue.id}
Title: ${issue.title}
Description: ${issue.description}
Reported By: ${issue.reportedBy}
Reported Date: ${issue.reportedDate}
Priority: ${classification?.priority || "unclassified"}
Priority Reasoning: ${classification?.reasoning || "N/A"}
`;
    })
    .join("\n---\n");

  const reportSummarySection = `
Total Reports: ${context.reportSummary.totalReports}
Submitted Reports: ${context.reportSummary.submittedReports}
Pending Reports: ${context.reportSummary.pendingReports}
Overall Progress: ${context.reportSummary.overallProgress}
`;

  const prompt = `You are an AI agent responsible for generating a comprehensive daily report for the department head based on extracted issues and their priority classifications.

Report Generation Time: ${reportGenerationTime}
Department Head Email: ${departmentHeadEmail}

=== REPORT SUMMARY ===
${reportSummarySection}

=== EXTRACTED ISSUES AND PRIORITY CLASSIFICATIONS ===
${issuesSection}

Your task:
1. Generate a well-structured report summarizing the overall progress and key issues
2. Create a prioritized issue list organized by priority level (critical, high, medium, low)
3. Identify any escalation flags that require human review:
   - Unusual or unexpected issues
   - Conflicting priority classifications
   - Critical risk issues
   - Incomplete or unclear data
4. Format the output as a professional report suitable for department head review

Output format:
- Report Content: A comprehensive summary of daily progress and issues
- Priority List Content: Issues organized by priority with brief descriptions
- Escalation Flags: Array of items requiring human review with reasoning

Ensure the report is clear, actionable, and highlights the most critical items first.`;

  return prompt;
}
