// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptInput {
  reportContent: string;
  extractedIssues: Array<{
    id: string;
    title: string;
    description: string;
    category: string;
  }>;
  teamMembers: Array<{
    id: string;
    name: string;
    department: string;
  }>;
  priorityClassificationRules: {
    critical: string[];
    high: string[];
    medium: string[];
    low: string[];
  };
  previousPriorities?: Record<string, string>;
}

export interface Action04PromptOutput {
  classifiedIssues: Array<{
    issueId: string;
    title: string;
    priority: "critical" | "high" | "medium" | "low";
    reasoning: string;
    affectedMembers: string[];
    recommendedAction: string;
  }>;
  priorityGroups: {
    critical: Array<{
      issueId: string;
      title: string;
      reasoning: string;
    }>;
    high: Array<{
      issueId: string;
      title: string;
      reasoning: string;
    }>;
    medium: Array<{
      issueId: string;
      title: string;
      reasoning: string;
    }>;
    low: Array<{
      issueId: string;
      title: string;
      reasoning: string;
    }>;
  };
  escalationRequired: boolean;
  escalationReason?: string;
  summaryForLeader: string;
}

export function buildAction04Prompt(input: Action04PromptInput): string {
  const rulesDescription = Object.entries(input.priorityClassificationRules)
    .map(
      ([priority, keywords]) =>
        `${priority.toUpperCase()}: ${keywords.join(", ")}`
    )
    .join("\n");

  const issuesDescription = input.extractedIssues
    .map(
      (issue) =>
        `- [${issue.id}] ${issue.title}\n  Category: ${issue.category}\n  Description: ${issue.description}`
    )
    .join("\n");

  const membersDescription = input.teamMembers
    .map((member) => `- ${member.name} (${member.department})`)
    .join("\n");

  const previousPrioritiesContext =
    input.previousPriorities && Object.keys(input.previousPriorities).length > 0
      ? `\n\nPrevious Priority Classifications:\n${Object.entries(input.previousPriorities)
          .map(([issueId, priority]) => `- Issue ${issueId}: ${priority}`)
          .join("\n")}`
      : "";

  return `You are an AI agent responsible for classifying and prioritizing issues extracted from daily reports.

Your task is to analyze the following issues and classify them by priority level based on the provided rules and context.

PRIORITY CLASSIFICATION RULES:
${rulesDescription}

EXTRACTED ISSUES TO CLASSIFY:
${issuesDescription}

TEAM MEMBERS CONTEXT:
${membersDescription}

REPORT CONTENT SUMMARY:
${input.reportContent}
${previousPrioritiesContext}

CLASSIFICATION REQUIREMENTS:
1. Analyze each issue against the priority classification rules
2. Determine the appropriate priority level (critical, high, medium, low)
3. Identify which team members are affected by each issue
4. Provide clear reasoning for each classification
5. Recommend specific actions for critical and high-priority issues
6. Determine if escalation to leadership is required
7. Create a summary suitable for presentation to the team leader

OUTPUT FORMAT:
Return a JSON object with the following structure:
{
  "classifiedIssues": [
    {
      "issueId": "string",
      "title": "string",
      "priority": "critical|high|medium|low",
      "reasoning": "string explaining the priority classification",
      "affectedMembers": ["member_id"],
      "recommendedAction": "string with specific action recommendation"
    }
  ],
  "priorityGroups": {
    "critical": [...],
    "high": [...],
    "medium": [...],
    "low": [...]
  },
  "escalationRequired": boolean,
  "escalationReason": "string if escalation is required",
  "summaryForLeader": "string with executive summary of all issues and priorities"
}

Ensure all classifications are consistent, well-reasoned, and actionable.`;
}
