// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportContent: string;
  previousIssues?: string[];
  teamContext?: string;
}

interface Action03PromptOutput {
  extractedIssues: Array<{
    issue: string;
    description: string;
    affectedMembers?: string[];
  }>;
  priorityClassification: Array<{
    issue: string;
    priority: "critical" | "high" | "medium" | "low";
    reasoning: string;
  }>;
  bottlenecks: string[];
  recommendations: string[];
}

function buildAction03Prompt(input: Action03PromptInput): string {
  const sections: string[] = [];

  sections.push("# 課題抽出・優先度判定プロンプト");
  sections.push("");

  sections.push("## 目的");
  sections.push(
    "日報内容から課題・ボトルネックを自動抽出し、優先度を判定・分類します。"
  );
  sections.push("");

  sections.push("## 日報内容");
  sections.push(input.reportContent);
  sections.push("");

  if (input.previousIssues && input.previousIssues.length > 0) {
    sections.push("## 前回抽出された課題");
    input.previousIssues.forEach((issue, index) => {
      sections.push(`${index + 1}. ${issue}`);
    });
    sections.push("");
  }

  if (input.teamContext) {
    sections.push("## チームコンテキスト");
    sections.push(input.teamContext);
    sections.push("");
  }

  sections.push("## 実行タスク");
  sections.push("1. 日報から課題・ボトルネックを抽出");
  sections.push("2. 各課題の優先度を判定（critical/high/medium/low）");
  sections.push("3. 優先度判定の根拠を記述");
  sections.push("4. 推奨アクションを提示");
  sections.push("");

  sections.push("## 優先度判定基準");
  sections.push("- critical: 朝会開始前に対応が必要、プロジェクト全体に影響");
  sections.push("- high: 本日中に対応が必要、複数チームに影響");
  sections.push("- medium: 今週中に対応が必要、特定チームに影響");
  sections.push("- low: 来週以降の対応可能、個別対応で対応可能");
  sections.push("");

  sections.push("## 出力形式");
  sections.push("JSON形式で以下の構造で返却してください:");
  sections.push("{");
  sections.push('  "extractedIssues": [');
  sections.push("    {");
  sections.push('      "issue": "課題タイトル",');
  sections.push('      "description": "詳細説明",');
  sections.push('      "affectedMembers": ["メンバー1", "メンバー2"]');
  sections.push("    }");
  sections.push("  ],");
  sections.push('  "priorityClassification": [');
  sections.push("    {");
  sections.push('      "issue": "課題タイトル",');
  sections.push('      "priority": "critical|high|medium|low",');
  sections.push('      "reasoning": "優先度判定の根拠"');
  sections.push("    }");
  sections.push("  ],");
  sections.push('  "bottlenecks": ["ボトルネック1", "ボトルネック2"],');
  sections.push('  "recommendations": ["推奨アクション1", "推奨アクション2"]');
  sections.push("}");

  return sections.join("\n");
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
export type { Action03PromptInput, Action03PromptOutput };
