// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptInput {
  reportDate: string;
  engineerName: string;
  engineerId: string;
  previousReportContent?: string;
  systemContext?: Record<string, unknown>;
}

export interface Action01PromptOutput {
  templateContent: string;
  distributionChannels: string[];
  scheduledTime: string;
}

export function buildAction01Prompt(input: Action01PromptInput): string {
  const { reportDate, engineerName, engineerId, previousReportContent, systemContext } = input;

  const previousContext = previousReportContent
    ? `\n前日の日報内容:\n${previousReportContent}`
    : "";

  const systemInfo = systemContext
    ? `\nシステムコンテキスト: ${JSON.stringify(systemContext)}`
    : "";

  return `あなたは朝会報告管理システムのAIエージェントです。

【タスク】
エンジニア「${engineerName}」(ID: ${engineerId})に対して、${reportDate}の日報テンプレートを自動生成して配信してください。

【日報テンプレートの構成要素】
1. 昨日の実績（前日の進捗状況、完了したタスク）
2. 本日の予定（本日実施予定のタスク、目標）
3. 抱えている課題（現在の課題、ボトルネック、懸念事項）

【出力形式】
以下のJSON形式で返してください:
{
  "templateContent": "生成されたテンプレート本文",
  "distributionChannels": ["email", "chat"],
  "scheduledTime": "配信予定時刻（HH:MM形式）"
}

【前提条件】
- テンプレートは簡潔で、エンジニアが5分以内に入力完了できる分量にしてください
- 前日の内容がある場合は参考にしてください${previousContext}
${systemInfo}

【制約】
- テンプレートは日本語で作成してください
- 配信チャネルはメール、チャットツール、または両方を指定してください
- 配信時刻は営業開始時刻の30分前を推奨してください`;
}
