// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-05.ts

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Context {
  confirmationEmailContent: string;
  reportSubmissionDeadline: string;
  currentTimestamp: string;
  previousEscalations: Array<{
    employeeId: string;
    escalationCount: number;
    lastEscalationTime: string;
  }>;
  escalationRules: {
    maxEscalationCount: number;
    escalationIntervalMinutes: number;
    considerLateAfterMinutes: number;
  };
}

export interface ExtractedIssue {
  issueId: string;
  description: string;
  affectedEmployees: string[];
  severity: "critical" | "high" | "medium" | "low";
  category: string;
  detectedAt: string;
}

export interface PrioritizedIssue extends ExtractedIssue {
  priority: number;
  priorityReason: string;
  recommendedAction: string;
}

export interface Action05Output {
  extractedIssues: ExtractedIssue[];
  prioritizedIssues: PrioritizedIssue[];
  escalationRecommendations: Array<{
    employeeId: string;
    shouldEscalate: boolean;
    reason: string;
    recommendedAction: string;
  }>;
  summaryReport: {
    totalIssuesFound: number;
    criticalIssueCount: number;
    escalationCandidateCount: number;
    generatedAt: string;
  };
}

export function buildAction05Prompt(context: Action05Context): string {
  const {
    confirmationEmailContent,
    reportSubmissionDeadline,
    currentTimestamp,
    previousEscalations,
    escalationRules,
  } = context;

  const escalationHistory = previousEscalations
    .map(
      (e) =>
        `- Employee ${e.employeeId}: ${e.escalationCount} escalations (last: ${e.lastEscalationTime})`
    )
    .join("\n");

  const prompt = `You are an AI agent responsible for analyzing confirmation email content to extract issues, prioritize them, and determine escalation recommendations.

## Current Context
- Confirmation Email Content:
${confirmationEmailContent}

- Report Submission Deadline: ${reportSubmissionDeadline}
- Current Timestamp: ${currentTimestamp}
- Max Escalation Count: ${escalationRules.maxEscalationCount}
- Escalation Interval: ${escalationRules.escalationIntervalMinutes} minutes
- Consider Late After: ${escalationRules.considerLateAfterMinutes} minutes

## Previous Escalation History
${escalationHistory || "No previous escalations"}

## Your Tasks

1. **Extract Issues**: Analyze the confirmation email content and identify all issues, bottlenecks, or anomalies mentioned. For each issue:
   - Assign a unique issue ID
   - Provide a clear description
   - Identify affected employees
   - Determine severity (critical/high/medium/low)
   - Categorize the issue

2. **Prioritize Issues**: For each extracted issue, determine:
   - Priority number (1 = highest)
   - Reason for the priority
   - Recommended action

3. **Escalation Recommendations**: Based on the email content and escalation history:
   - Identify employees who should receive escalation notifications
   - Provide reasoning for each escalation decision
   - Recommend specific actions (email/chat notification)
   - Consider escalation count limits and intervals

4. **Generate Summary Report**: Create a summary with:
   - Total issues found
   - Count of critical issues
   - Count of escalation candidates
   - Generation timestamp

## Output Format
Return a JSON object with the following structure:
{
  "extractedIssues": [
    {
      "issueId": "string",
      "description": "string",
      "affectedEmployees": ["string"],
      "severity": "critical|high|medium|low",
      "category": "string",
      "detectedAt": "ISO timestamp"
    }
  ],
  "prioritizedIssues": [
    {
      "issueId": "string",
      "description": "string",
      "affectedEmployees": ["string"],
      "severity": "critical|high|medium|low",
      "category": "string",
      "detectedAt": "ISO timestamp",
      "priority": number,
      "priorityReason": "string",
      "recommendedAction": "string"
    }
  ],
  "escalationRecommendations": [
    {
      "employeeId": "string",
      "shouldEscalate": boolean,
      "reason": "string",
      "recommendedAction": "string"
    }
  ],
  "summaryReport": {
    "totalIssuesFound": number,
    "criticalIssueCount": number,
    "escalationCandidateCount": number,
    "generatedAt": "ISO timestamp"
  }
}

Ensure all timestamps are in ISO 8601 format. Be thorough in issue extraction and prioritization.`;

  return prompt;
}
