// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportDeadline: string;
  reminderThreshold: number;
  escalationRules: {
    maxReminderCount: number;
    escalationAfterDays: number;
  };
  teamMembers: Array<{
    id: string;
    name: string;
    email: string;
    department: string;
  }>;
  submissionStatus: Array<{
    memberId: string;
    submitted: boolean;
    submittedAt?: string;
    reminderCount: number;
  }>;
}

interface Action03PromptOutput {
  version: string;
  systemPrompt: string;
  userPrompt: string;
  context: {
    action: string;
    stage: string;
    objective: string;
  };
}

function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const systemPrompt = `You are an AI agent responsible for identifying non-submitting and delayed team members from confirmation email contents and determining escalation targets. Your role is to:
1. Parse confirmation email contents to identify members who have not submitted reports
2. Determine which members require escalation based on submission deadline and reminder rules
3. Classify members by escalation priority
4. Prepare escalation targets for automated notification dispatch

Follow these rules:
- A member is considered non-submitting if their submission status is false
- Escalation is triggered when: (a) submission deadline has passed, or (b) reminder count exceeds threshold
- Escalation priority is determined by: days overdue, reminder count, and department criticality
- Maintain audit trail of all escalation decisions`;

  const nonSubmittingMembers = input.submissionStatus
    .filter((status) => !status.submitted)
    .map((status) => {
      const member = input.teamMembers.find((m) => m.id === status.memberId);
      return {
        memberId: status.memberId,
        name: member?.name || "Unknown",
        email: member?.email || "",
        department: member?.department || "",
        reminderCount: status.reminderCount,
      };
    });

  const escalationTargets = nonSubmittingMembers.filter((member) => {
    const daysOverdue = calculateDaysOverdue(input.reportDeadline);
    const shouldEscalate =
      daysOverdue > 0 ||
      member.reminderCount >= input.escalationRules.maxReminderCount;
    return shouldEscalate;
  });

  const userPrompt = `Process the following team submission status and determine escalation targets:

Report Deadline: ${input.reportDeadline}
Reminder Threshold: ${input.reminderThreshold} days
Max Reminder Count: ${input.escalationRules.maxReminderCount}
Escalation After Days: ${input.escalationRules.escalationAfterDays}

Non-Submitting Members:
${JSON.stringify(nonSubmittingMembers, null, 2)}

Escalation Targets (preliminary):
${JSON.stringify(escalationTargets, null, 2)}

Tasks:
1. Validate each escalation target against the escalation rules
2. Assign escalation priority (HIGH, MEDIUM, LOW) based on days overdue and reminder count
3. Determine notification method (email, chat, or both)
4. Generate escalation summary for department heads
5. Identify any special cases requiring human review

Provide structured output with:
- Confirmed escalation targets with priority levels
- Recommended notification methods
- Special cases flagged for human review
- Audit trail of escalation decisions`;

  return {
    version: ACTION_03_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    context: {
      action: "identify_and_escalate_non_submitters",
      stage: "escalation_determination",
      objective:
        "Identify non-submitting members and determine escalation targets based on submission deadline and reminder rules",
    },
  };
}

function calculateDaysOverdue(deadline: string): number {
  const deadlineDate = new Date(deadline);
  const now = new Date();
  const diffTime = now.getTime() - deadlineDate.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return Math.max(0, diffDays);
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
