// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportContent: string;
  engineerName: string;
  submissionDate: string;
  validationRules?: {
    minLength?: number;
    maxLength?: number;
    requiredFields?: string[];
  };
}

export interface Action02PromptOutput {
  isValid: boolean;
  validationErrors: string[];
  sanitizedContent: string;
  summary: string;
}

export function buildAction02Prompt(input: Action02PromptInput): string {
  const {
    reportContent,
    engineerName,
    submissionDate,
    validationRules = {
      minLength: 10,
      maxLength: 5000,
      requiredFields: ["yesterday", "today", "issues"],
    },
  } = input;

  const requiredFieldsText =
    validationRules.requiredFields?.join(", ") || "yesterday, today, issues";

  return `You are a validation agent for the daily report management system.

Your task is to validate the following daily report submission:

**Engineer Name:** ${engineerName}
**Submission Date:** ${submissionDate}
**Report Content:**
${reportContent}

**Validation Rules:**
- Minimum content length: ${validationRules.minLength} characters
- Maximum content length: ${validationRules.maxLength} characters
- Required sections: ${requiredFieldsText}
- Content must be professional and relevant to work activities
- No offensive or inappropriate language
- Must contain specific, actionable information

Please perform the following validations:
1. Check if the report meets the minimum and maximum length requirements
2. Verify that all required sections are present
3. Assess the quality and appropriateness of the content
4. Identify any missing or incomplete information
5. Provide a sanitized version of the content if valid

Return your analysis in the following JSON format:
{
  "isValid": boolean,
  "validationErrors": string[],
  "sanitizedContent": string,
  "summary": string
}

Be strict but fair in your validation. Only mark as invalid if there are genuine issues that would prevent proper report processing.`;
}
