// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportContent: string;
  submissionDeadline: string;
  escalationThreshold: number;
  previousEscalationCount: number;
}

export interface Action02PromptOutput {
  shouldEscalate: boolean;
  escalationReason: string;
  recommendedAction: string;
  riskLevel: "low" | "medium" | "high";
}

export function buildAction02Prompt(input: Action02PromptInput): string {
  const {
    reportContent,
    submissionDeadline,
    escalationThreshold,
    previousEscalationCount,
  } = input;

  const escalationStatus =
    previousEscalationCount >= escalationThreshold ? "exceeded" : "within";

  return `You are an AI agent responsible for analyzing daily report submissions and determining escalation conditions.

Current Report Analysis:
- Report Content: ${reportContent}
- Submission Deadline: ${submissionDeadline}
- Escalation Threshold: ${escalationThreshold}
- Previous Escalation Count: ${previousEscalationCount}
- Escalation Status: ${escalationStatus}

Your task is to:
1. Analyze the report content for completeness and appropriateness
2. Determine if escalation is necessary based on the escalation conditions
3. Identify the specific reason for escalation if applicable
4. Recommend the appropriate action (notify manager, send reminder, flag for review, etc.)
5. Assess the risk level (low, medium, high)

Escalation Conditions:
- Report content is incomplete or inappropriate
- Submission deadline has been significantly exceeded
- System error occurred during registration
- Multiple escalations have already been triggered for the same employee

Provide your analysis in a structured format with clear reasoning for each decision.`;
}
