// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-4-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptInput {
  reportDate: string;
  engineerName: string;
  engineerId: string;
  previousReportContent?: string;
  systemContext?: Record<string, unknown>;
}

export interface Action01PromptOutput {
  prompt: string;
  version: string;
  metadata: {
    timestamp: string;
    engineerId: string;
    reportDate: string;
  };
}

export function buildAction01Prompt(input: Action01PromptInput): Action01PromptOutput {
  const {
    reportDate,
    engineerName,
    engineerId,
    previousReportContent = "",
    systemContext = {},
  } = input;

  const basePrompt = `あなたは朝会報告管理システムのAIエージェントです。以下の情報に基づいて、エンジニアの日報テンプレートを自動生成して配信する準備を行ってください。

【対象エンジニア情報】
- 名前: ${engineerName}
- ID: ${engineerId}
- 報告日: ${reportDate}

【前日の日報内容】
${previousReportContent || "（初回または前日の日報がありません）"}

【システムコンテキスト】
${JSON.stringify(systemContext, null, 2)}

【実行タスク】
1. 前日の日報テンプレートを参考に、本日の日報テンプレートを自動生成してください
2. テンプレートには以下のセクションを含めてください：
   - 昨日の実績（前日の予定との比較）
   - 本日の予定
   - 抱えている課題
   - その他の連絡事項
3. エンジニアが入力しやすいように、具体的な記入例を示してください
4. 生成したテンプレートをJSON形式で出力してください

【出力形式】
\`\`\`json
{
  "templateId": "string",
  "engineerId": "${engineerId}",
  "reportDate": "${reportDate}",
  "sections": [
    {
      "name": "string",
      "label": "string",
      "placeholder": "string",
      "example": "string",
      "required": boolean
    }
  ],
  "readyForDistribution": boolean
}
\`\`\``;

  return {
    prompt: basePrompt,
    version: ACTION_01_PROMPT_VERSION,
    metadata: {
      timestamp: new Date().toISOString(),
      engineerId,
      reportDate,
    },
  };
}
