// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/orchestrator.ts
export { runTx1Imp1Agent } from "../../logic/it-1";
export type { Tx1Imp1AiClient } from "../../logic/it-1";
