// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/db/connection.ts

// src/db/connection.ts

interface QueryResult {
  [key: string]: unknown;
}

interface DatabaseConnection {
  query(sql: string, params?: unknown[]): Promise<QueryResult[]>;
}

// In-memory database implementation
class InMemoryDatabase implements DatabaseConnection {
  private tables: Map<string, Map<string, QueryResult>> = new Map();
  private sequences: Map<string, number> = new Map();

  constructor() {
    this.initializeTables();
  }

  private initializeTables(): void {
    this.tables.set('departments', new Map());
    this.tables.set('users', new Map());
    this.tables.set('unreported_members', new Map());
    this.tables.set('mail_queue', new Map());
    this.tables.set('audit_log', new Map());
  }

  async query(sql: string, params: unknown[] = []): Promise<QueryResult[]> {
    const trimmedSql = sql.trim();

    // DELETE queries
    if (trimmedSql.toUpperCase().startsWith('DELETE')) {
      return this.handleDelete(trimmedSql, params);
    }

    // INSERT queries
    if (trimmedSql.toUpperCase().startsWith('INSERT')) {
      return this.handleInsert(trimmedSql, params);
    }

    // SELECT queries
    if (trimmedSql.toUpperCase().startsWith('SELECT')) {
      return this.handleSelect(trimmedSql, params);
    }

    return [];
  }

  private handleDelete(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const deleteMatch = sql.match(/DELETE\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+))?/i);
    if (!deleteMatch) {
      return Promise.resolve([]);
    }

    const tableName = deleteMatch[1].toLowerCase();
    const whereClause = deleteMatch[2];

    const table = this.tables.get(tableName);
    if (!table) {
      return Promise.resolve([]);
    }

    if (!whereClause) {
      table.clear();
      return Promise.resolve([]);
    }

    const keysToDelete: string[] = [];
    table.forEach((row, key) => {
      if (this.evaluateWhere(whereClause, row, params)) {
        keysToDelete.push(key);
      }
    });

    keysToDelete.forEach((key) => table.delete(key));
    return Promise.resolve([]);
  }

  private handleInsert(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const insertMatch = sql.match(
      /INSERT\s+INTO\s+(\w+)\s*\(([^)]+)\)\s+VALUES\s*\(([^)]+)\)(?:\s+RETURNING\s+(.+))?/i
    );
    if (!insertMatch) {
      return Promise.resolve([]);
    }

    const tableName = insertMatch[1].toLowerCase();
    const columns = insertMatch[2].split(',').map((c) => c.trim().toLowerCase());
    const returningClause = insertMatch[4];

    const table = this.tables.get(tableName);
    if (!table) {
      return Promise.resolve([]);
    }

    const row: QueryResult = {};
    columns.forEach((col, idx) => {
      row[col] = params[idx];
    });

    const key = `${tableName}_${Date.now()}_${Math.random()}`;
    table.set(key, row);

    if (returningClause) {
      const returningColumns = returningClause
        .split(',')
        .map((c) => c.trim().toLowerCase());
      const result: QueryResult = {};
      returningColumns.forEach((col) => {
        result[col] = row[col];
      });
      return Promise.resolve([result]);
    }

    return Promise.resolve([]);
  }

  private handleSelect(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const selectMatch = sql.match(
      /SELECT\s+(.+?)\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+))?/i
    );
    if (!selectMatch) {
      return Promise.resolve([]);
    }

    const selectClause = selectMatch[1].trim();
    const tableName = selectMatch[2].toLowerCase();
    const whereClause = selectMatch[3];

    const table = this.tables.get(tableName);
    if (!table) {
      return Promise.resolve([]);
    }

    let results: QueryResult[] = [];

    table.forEach((row) => {
      if (!whereClause || this.evaluateWhere(whereClause, row, params)) {
        results.push(row);
      }
    });

    if (selectClause === '*') {
      return Promise.resolve(results);
    }

    const columns = selectClause
      .split(',')
      .map((c) => c.trim().toLowerCase());
    const projectedResults = results.map((row) => {
      const projected: QueryResult = {};
      columns.forEach((col) => {
        if (col === 'count(*)' || col === 'count(*) as cnt') {
          projected['cnt'] = results.length;
        } else {
          projected[col] = row[col];
        }
      });
      return projected;
    });

    return Promise.resolve(projectedResults);
  }

  private evaluateWhere(
    whereClause: string,
    row: QueryResult,
    params: unknown[]
  ): boolean {
    const eqMatch = whereClause.match(/(\w+)\s*=\s*\?/i);
    if (eqMatch) {
      const column = eqMatch[1].toLowerCase();
      const paramValue = params[0];
      return row[column] === paramValue;
    }

    return true;
  }
}

let connectionInstance: DatabaseConnection | null = null;

export function getConnection(): DatabaseConnection {
  if (!connectionInstance) {
    connectionInstance = new InMemoryDatabase();
  }
  return connectionInstance;
}
