// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/db/connection.ts

// src/db/connection.ts

interface QueryResult {
  [key: string]: unknown;
}

interface DbConnection {
  query(sql: string, params?: unknown[]): Promise<QueryResult[]>;
}

// In-memory database implementation
class InMemoryConnection implements DbConnection {
  private tables: Map<string, Map<string, QueryResult>> = new Map();
  private sequences: Map<string, number> = new Map();

  constructor() {
    this.initializeTables();
  }

  private initializeTables(): void {
    this.tables.set('departments', new Map());
    this.tables.set('users', new Map());
    this.tables.set('unreported_members', new Map());
    this.tables.set('mail_queue', new Map());
    this.tables.set('audit_log', new Map());
  }

  async query(sql: string, params: unknown[] = []): Promise<QueryResult[]> {
    const trimmedSql = sql.trim().toUpperCase();

    if (trimmedSql.startsWith('DELETE FROM')) {
      return this.handleDelete(sql, params);
    }

    if (trimmedSql.startsWith('INSERT INTO')) {
      return this.handleInsert(sql, params);
    }

    if (trimmedSql.startsWith('SELECT')) {
      return this.handleSelect(sql, params);
    }

    return [];
  }

  private handleDelete(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const tableMatch = sql.match(/DELETE FROM\s+(\w+)/i);
    if (!tableMatch) return Promise.resolve([]);

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return Promise.resolve([]);

    const whereMatch = sql.match(/WHERE\s+(.+?)(?:;|$)/i);
    if (!whereMatch) {
      table.clear();
      return Promise.resolve([]);
    }

    const whereClause = whereMatch[1];
    if (whereClause.includes('department_id = ?')) {
      const deptId = params[0];
      const keysToDelete: string[] = [];
      table.forEach((row, key) => {
        if (row['department_id'] === deptId) {
          keysToDelete.push(key);
        }
      });
      keysToDelete.forEach((key) => table.delete(key));
    } else if (whereClause.includes('list_id = ?')) {
      const listId = params[0];
      table.delete(String(listId));
    } else if (whereClause.includes('status = ?')) {
      const status = params[0];
      const keysToDelete: string[] = [];
      table.forEach((row, key) => {
        if (row['status'] === status) {
          keysToDelete.push(key);
        }
      });
      keysToDelete.forEach((key) => table.delete(key));
    }

    return Promise.resolve([]);
  }

  private handleInsert(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const tableMatch = sql.match(/INSERT INTO\s+(\w+)/i);
    if (!tableMatch) return Promise.resolve([]);

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return Promise.resolve([]);

    const columnsMatch = sql.match(/\(([^)]+)\)/);
    if (!columnsMatch) return Promise.resolve([]);

    const columns = columnsMatch[1]
      .split(',')
      .map((c) => c.trim().toLowerCase());

    const row: QueryResult = {};
    let paramIndex = 0;

    for (const col of columns) {
      if (col !== 'created_at' && col !== 'now()') {
        row[col] = params[paramIndex] ?? null;
        paramIndex++;
      } else if (col === 'created_at' || col === 'now()') {
        row['created_at'] = new Date().toISOString();
      }
    }

    const hasReturning = sql.toUpperCase().includes('RETURNING');
    let key = String(row['id'] ?? row['list_id'] ?? row['user_id'] ?? Date.now());

    if (tableName === 'users' && row['user_id']) {
      key = String(row['user_id']);
    } else if (tableName === 'departments' && row['department_id']) {
      key = String(row['department_id']);
    } else if (tableName === 'unreported_members' && row['list_id']) {
      key = String(row['list_id']);
    } else if (tableName === 'audit_log') {
      key = `${row['action']}_${Date.now()}`;
    }

    table.set(key, row);

    if (hasReturning) {
      return Promise.resolve([row]);
    }

    return Promise.resolve([]);
  }

  private handleSelect(sql: string, params: unknown[]): Promise<QueryResult[]> {
    const tableMatch = sql.match(/FROM\s+(\w+)/i);
    if (!tableMatch) return Promise.resolve([]);

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return Promise.resolve([]);

    const countMatch = sql.match(/COUNT\(\*\)\s+as\s+(\w+)/i);
    if (countMatch) {
      const countAlias = countMatch[1].toLowerCase();
      const result: QueryResult = {};
      result[countAlias] = table.size;
      return Promise.resolve([result]);
    }

    const whereMatch = sql.match(/WHERE\s+(.+?)(?:;|$)/i);
    if (!whereMatch) {
      return Promise.resolve(Array.from(table.values()));
    }

    const whereClause = whereMatch[1];
    const results: QueryResult[] = [];

    if (whereClause.includes('status = ?')) {
      const status = params[0];
      table.forEach((row) => {
        if (row['status'] === status) {
          results.push(row);
        }
      });
    }

    return Promise.resolve(results);
  }
}

let connectionInstance: DbConnection | null = null;

export function getConnection(): DbConnection {
  if (!connectionInstance) {
    connectionInstance = new InMemoryConnection();
  }
  return connectionInstance;
}
