// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/db/connection.ts

// src/db/connection.ts

interface QueryResult {
  [key: string]: unknown;
}

interface DbConnection {
  query(sql: string, params?: unknown[]): Promise<QueryResult[]>;
}

// In-memory database implementation
class InMemoryConnection implements DbConnection {
  private tables: Map<string, Map<string, QueryResult>> = new Map();
  private sequences: Map<string, number> = new Map();

  constructor() {
    this.initializeTables();
  }

  private initializeTables(): void {
    this.tables.set('departments', new Map());
    this.tables.set('users', new Map());
    this.tables.set('unreported_members', new Map());
    this.tables.set('mail_queue', new Map());
    this.tables.set('audit_log', new Map());
  }

  async query(sql: string, params: unknown[] = []): Promise<QueryResult[]> {
    const trimmedSql = sql.trim();

    // DELETE queries
    if (trimmedSql.toUpperCase().startsWith('DELETE FROM')) {
      return this.handleDelete(trimmedSql, params);
    }

    // INSERT queries
    if (trimmedSql.toUpperCase().startsWith('INSERT INTO')) {
      return this.handleInsert(trimmedSql, params);
    }

    // SELECT queries
    if (trimmedSql.toUpperCase().startsWith('SELECT')) {
      return this.handleSelect(trimmedSql, params);
    }

    return [];
  }

  private handleDelete(sql: string, params: unknown[]): QueryResult[] {
    const tableMatch = sql.match(/DELETE FROM\s+(\w+)/i);
    if (!tableMatch) return [];

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return [];

    const whereMatch = sql.match(/WHERE\s+(.+?)(?:;|$)/i);
    if (!whereMatch) {
      table.clear();
      return [];
    }

    const whereClause = whereMatch[1];
    const keysToDelete: string[] = [];

    table.forEach((row, key) => {
      if (this.evaluateWhere(whereClause, row, params)) {
        keysToDelete.push(key);
      }
    });

    keysToDelete.forEach((key) => table.delete(key));
    return [];
  }

  private handleInsert(sql: string, params: unknown[]): QueryResult[] {
    const tableMatch = sql.match(/INSERT INTO\s+(\w+)/i);
    if (!tableMatch) return [];

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return [];

    const columnsMatch = sql.match(/\(([^)]+)\)/);
    if (!columnsMatch) return [];

    const columns = columnsMatch[1]
      .split(',')
      .map((c) => c.trim().toLowerCase());

    const row: QueryResult = {};
    columns.forEach((col, idx) => {
      row[col] = params[idx];
    });

    const returningMatch = sql.match(/RETURNING\s+(\w+)/i);
    const keyColumn = returningMatch ? returningMatch[1].toLowerCase() : null;

    if (keyColumn && row[keyColumn]) {
      const key = String(row[keyColumn]);
      table.set(key, row);

      if (returningMatch) {
        return [{ [keyColumn]: row[keyColumn] }];
      }
    } else {
      const key = `row_${table.size}`;
      table.set(key, row);
    }

    return [];
  }

  private handleSelect(sql: string, params: unknown[]): QueryResult[] {
    const countMatch = sql.match(/COUNT\(\*\)\s+as\s+(\w+)/i);
    if (countMatch) {
      const tableMatch = sql.match(/FROM\s+(\w+)/i);
      if (!tableMatch) return [];

      const tableName = tableMatch[1].toLowerCase();
      const table = this.tables.get(tableName);
      if (!table) return [{ [countMatch[1]]: 0 }];

      const whereMatch = sql.match(/WHERE\s+(.+?)(?:;|$)/i);
      if (!whereMatch) {
        return [{ [countMatch[1]]: table.size }];
      }

      const whereClause = whereMatch[1];
      let count = 0;
      table.forEach((row) => {
        if (this.evaluateWhere(whereClause, row, params)) {
          count++;
        }
      });

      return [{ [countMatch[1]]: count }];
    }

    const tableMatch = sql.match(/FROM\s+(\w+)/i);
    if (!tableMatch) return [];

    const tableName = tableMatch[1].toLowerCase();
    const table = this.tables.get(tableName);
    if (!table) return [];

    const results: QueryResult[] = [];
    table.forEach((row) => {
      results.push(row);
    });

    return results;
  }

  private evaluateWhere(
    whereClause: string,
    row: QueryResult,
    params: unknown[]
  ): boolean {
    if (whereClause.includes('=')) {
      const parts = whereClause.split('=').map((p) => p.trim());
      const columnName = parts[0].toLowerCase();
      const paramIndex = 0;

      if (parts[1] === '?') {
        return row[columnName] === params[paramIndex];
      }
    }

    return true;
  }
}

let connectionInstance: DbConnection | null = null;

export function getConnection(): DbConnection {
  if (!connectionInstance) {
    connectionInstance = new InMemoryConnection();
  }
  return connectionInstance;
}
