// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/db/schema.ts

export interface User {
  user_id: string;
  user_name: string;
  email: string;
  department_id: string;
  role: "manager" | "engineer";
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Department {
  department_id: string;
  department_name: string;
  parent_department_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface MorningReportSubmission {
  submission_id: string;
  user_id: string;
  submission_date: string;
  yesterday_achievement: string;
  today_plan: string;
  current_issues: string;
  submitted_at: string;
  created_at: string;
  updated_at: string;
}

export interface ReportSendHistory {
  send_history_id: string;
  submission_id: string;
  user_id: string;
  sent_at: string;
  send_status: "submitted" | "pending" | "failed";
  created_at: string;
}
