// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/types/audit.ts

export interface AuditLog {
  timestamp: string;
  operator_role: string;
  operation_name: string;
  result: "DENIED" | "ALLOWED" | "SUCCESS" | "FAILURE";
  reason: string;
  target_department_id?: string;
  target_manager_id?: string;
}
