// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/config/env.ts

/**
 * Environment variable management module for 朝会報告管理システム
 */

/**
 * Retrieves an environment variable by key
 * @param key - The environment variable key to retrieve
 * @returns The environment variable value, or undefined if not set
 */
export function getEnvVariable(key: string): string | undefined {
  return process.env[key];
}
