// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/config/env.ts

/**
 * 環境変数を取得する関数
 * @param key 環境変数のキー
 * @param defaultValue デフォルト値（オプション）
 * @returns 環境変数の値、またはデフォルト値
 */
export function getEnvVariable(
  key: string,
  defaultValue?: string
): string | undefined {
  return process.env[key] ?? defaultValue;
}
