// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface PromptContext {
  confirmationEmailContent: string;
  reportingDeadline: string;
  reminderThreshold: number;
  maxReminderAttempts: number;
}

interface IdentifiedMember {
  memberId: string;
  memberName: string;
  status: "not_submitted" | "delayed" | "submitted";
  submissionTime?: string;
  daysSinceDeadline?: number;
}

interface ReminderTarget {
  memberId: string;
  memberName: string;
  reminderCount: number;
  shouldRemind: boolean;
  reminderReason: string;
}

interface Action03PromptResult {
  version: string;
  identifiedMembers: IdentifiedMember[];
  reminderTargets: ReminderTarget[];
  analysisTimestamp: string;
  escalationFlags: string[];
}

function buildAction03Prompt(context: PromptContext): string {
  const prompt = `
You are an AI agent responsible for identifying non-submitting and delayed members from confirmation email content and determining reminder targets.

## Task
Analyze the confirmation email content and identify:
1. Members who have not submitted their daily reports
2. Members whose reports are delayed beyond the deadline
3. Determine which members should receive reminder notifications

## Input Context
- Confirmation Email Content: ${context.confirmationEmailContent}
- Reporting Deadline: ${context.reportingDeadline}
- Reminder Threshold (hours after deadline): ${context.reminderThreshold}
- Maximum Reminder Attempts: ${context.maxReminderAttempts}

## Output Requirements
Return a structured analysis containing:
1. List of identified members with their submission status
2. List of members to receive reminders with justification
3. Any escalation flags for exceptional cases
4. Timestamp of analysis

## Rules
- Only identify members explicitly mentioned in the confirmation email
- Mark status as "not_submitted", "delayed", or "submitted"
- Calculate days since deadline for delayed submissions
- Apply maximum reminder attempt limit
- Flag any members requiring escalation (multiple reminders without response)
`;
  return prompt;
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
export type { PromptContext, IdentifiedMember, ReminderTarget, Action03PromptResult };
