// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptInput {
  confirmationEmailContent: string;
  reportDeadline: string;
  currentTimestamp: string;
  previousEscalationCount?: Record<string, number>;
}

export interface Action01PromptOutput {
  missingReporters: Array<{
    employeeId: string;
    employeeName: string;
    reportStatus: "missing" | "delayed";
    daysSinceDeadline: number;
  }>;
  escalationTargets: Array<{
    employeeId: string;
    employeeName: string;
    escalationReason: string;
    escalationCount: number;
    shouldEscalate: boolean;
  }>;
  summary: {
    totalMissingCount: number;
    totalDelayedCount: number;
    escalationCandidateCount: number;
  };
}

export function buildAction01Prompt(
  input: Action01PromptInput
): string {
  const {
    confirmationEmailContent,
    reportDeadline,
    currentTimestamp,
    previousEscalationCount = {},
  } = input;

  const escalationCountSummary = Object.entries(previousEscalationCount)
    .map(([empId, count]) => `  - Employee ${empId}: ${count} escalations`)
    .join("\n");

  return `You are an AI agent responsible for identifying missing and delayed daily reports from the confirmation email content.

## Task: Identify Missing/Delayed Reporters and Determine Escalation Targets

### Input Information:
- Confirmation Email Content:
${confirmationEmailContent}

- Report Deadline: ${reportDeadline}
- Current Timestamp: ${currentTimestamp}
- Previous Escalation Count:
${escalationCountSummary || "  (No previous escalations)"}

### Your Responsibilities:

1. **Parse the confirmation email content** to extract:
   - List of employees who submitted reports
   - List of employees who did NOT submit reports
   - Submission timestamps for each report

2. **Classify reporters**:
   - Mark as "missing" if no report was submitted by the deadline
   - Mark as "delayed" if report was submitted after the deadline

3. **Calculate days since deadline** for delayed/missing reports

4. **Determine escalation targets** based on:
   - First escalation: Any missing or delayed report
   - Subsequent escalations: Only if previous escalation count >= 1
   - Maximum escalation threshold: 3 times per employee
   - Do NOT escalate if escalation count already reached 3

5. **Generate structured output** with:
   - List of missing reporters with details
   - List of escalation targets with reason and count
   - Summary statistics

### Output Format:
Return a JSON object with the following structure:
{
  "missingReporters": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "reportStatus": "missing" | "delayed",
      "daysSinceDeadline": number
    }
  ],
  "escalationTargets": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "escalationReason": "string",
      "escalationCount": number,
      "shouldEscalate": boolean
    }
  ],
  "summary": {
    "totalMissingCount": number,
    "totalDelayedCount": number,
    "escalationCandidateCount": number
  }
}

### Rules:
- Only include employees with missing or delayed reports
- Escalation count should reflect the number of times this employee has been escalated
- shouldEscalate should be true only if escalation count < 3
- Be precise with timestamps and deadline calculations
- Return valid JSON only, no additional text`;
}
