// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-03.ts

import type { Tx3Imp1AiClient } from '../orchestrator';

export const ACTION_03_PROMPT_VERSION = '1.0.0';

export interface Action03PromptInput {
  confirmationEmailContent: string;
  reportingDeadline: string;
  currentTimestamp: string;
  escalationThreshold: number;
}

export interface Action03PromptOutput {
  identifiedNonReporters: Array<{
    employeeId: string;
    employeeName: string;
    status: 'non_reported' | 'delayed';
    daysSinceDeadline: number;
  }>;
  escalationTargets: Array<{
    employeeId: string;
    employeeName: string;
    reason: string;
    priority: 'high' | 'medium' | 'low';
  }>;
  promptionPlan: {
    emailTargets: string[];
    chatTargets: string[];
    messageTemplate: string;
  };
}

export function buildAction03Prompt(input: Action03PromptInput): string {
  const {
    confirmationEmailContent,
    reportingDeadline,
    currentTimestamp,
    escalationThreshold,
  } = input;

  return `You are an AI agent responsible for identifying non-reporters and delayed reporters from confirmation email content, determining escalation targets, and planning prompt notifications.

## Task: Analyze Confirmation Email and Identify Non-Reporters

### Input Information:
- Confirmation Email Content:
${confirmationEmailContent}

- Reporting Deadline: ${reportingDeadline}
- Current Timestamp: ${currentTimestamp}
- Escalation Threshold (days): ${escalationThreshold}

### Your Responsibilities:

1. **Identify Non-Reporters and Delayed Reporters**
   - Parse the confirmation email content to extract the list of employees who have submitted reports
   - Identify employees who have NOT submitted reports (non_reported status)
   - Identify employees whose reports were submitted after the deadline (delayed status)
   - Calculate days since deadline for delayed reporters

2. **Determine Escalation Targets**
   - Apply escalation logic: if days since deadline >= escalation threshold, mark as escalation target
   - Assign priority levels:
     - high: days since deadline >= 2 * escalation threshold
     - medium: escalation threshold <= days since deadline < 2 * escalation threshold
     - low: days since deadline < escalation threshold but still delayed
   - Provide clear reason for each escalation

3. **Plan Promption Strategy**
   - Determine which employees should receive email prompts
   - Determine which employees should receive chat prompts
   - Create a professional, non-intrusive message template for prompts
   - Ensure message includes deadline information and gentle reminder tone

### Output Format:
Return a JSON object with the following structure:
{
  "identifiedNonReporters": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "status": "non_reported" | "delayed",
      "daysSinceDeadline": number
    }
  ],
  "escalationTargets": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "reason": "string",
      "priority": "high" | "medium" | "low"
    }
  ],
  "promptionPlan": {
    "emailTargets": ["employeeId1", "employeeId2"],
    "chatTargets": ["employeeId3"],
    "messageTemplate": "string"
  }
}

### Guidelines:
- Be accurate in identifying non-reporters from the email content
- Apply escalation rules consistently
- Create professional and respectful prompt messages
- Ensure no employee is missed in the analysis
- Prioritize high-priority escalations for immediate attention`;
}
