// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-03.ts

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface Action03PromptInput {
  confirmationEmailContent: string;
  reportingDeadline: string;
  currentTimestamp: string;
  escalationThreshold: number;
}

export interface Action03PromptOutput {
  identifiedNonReporters: Array<{
    employeeId: string;
    employeeName: string;
    status: "non-reported" | "delayed";
    daysOverdue: number;
  }>;
  urgencyLevel: "low" | "medium" | "high" | "critical";
  recommendedAction: string;
}

export function buildAction03Prompt(input: Action03PromptInput): string {
  const {
    confirmationEmailContent,
    reportingDeadline,
    currentTimestamp,
    escalationThreshold,
  } = input;

  const systemPrompt = `You are an AI agent responsible for identifying non-reporting and delayed reporting employees from confirmation email content.

Your task is to:
1. Parse the confirmation email content to identify which employees have not submitted their reports
2. Determine if any employees are delayed in their submissions
3. Assess the urgency level based on the time elapsed since the deadline
4. Recommend appropriate escalation actions

Reporting Deadline: ${reportingDeadline}
Current Timestamp: ${currentTimestamp}
Escalation Threshold (days): ${escalationThreshold}

Email Content to Analyze:
${confirmationEmailContent}

Provide your analysis in a structured format identifying:
- Each non-reporting or delayed employee with their ID and name
- The status (non-reported or delayed)
- Days overdue if applicable
- Overall urgency level
- Recommended action for escalation`;

  return systemPrompt;
}
