// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptContext {
  confirmationEmailContent: string;
  reportingDeadline: string;
  escalationThreshold: number;
  previousEscalationCount: Record<string, number>;
}

export interface Action04PromptResult {
  identifiedNonReporters: Array<{
    memberId: string;
    memberName: string;
    reportingStatus: "not_submitted" | "delayed";
    daysOverdue: number;
  }>;
  escalationTargets: Array<{
    memberId: string;
    memberName: string;
    escalationReason: string;
    escalationCount: number;
    shouldEscalate: boolean;
  }>;
  escalationMessages: Array<{
    targetMemberId: string;
    messageType: "email" | "chat";
    messageContent: string;
  }>;
  executionLog: Array<{
    timestamp: string;
    action: string;
    status: "success" | "failure";
    details: string;
  }>;
}

export function buildAction04Prompt(
  context: Action04PromptContext
): string {
  const systemPrompt = `You are an AI agent responsible for identifying non-reporting members from confirmation email content and executing escalation procedures.

Your task is to:
1. Parse the confirmation email content to identify members who have not submitted reports or submitted late
2. Determine which members should be escalated based on the escalation threshold and previous escalation count
3. Generate appropriate escalation messages (email or chat) for each target member
4. Log all actions and their results

Escalation Rules:
- A member should be escalated if they have not submitted a report by the deadline
- Consider the escalation threshold: ${context.escalationThreshold}
- Track previous escalation counts to avoid excessive notifications
- Provide clear reasoning for each escalation decision

Output Format:
Return a JSON object with the following structure:
{
  "identifiedNonReporters": [
    {
      "memberId": "string",
      "memberName": "string",
      "reportingStatus": "not_submitted" | "delayed",
      "daysOverdue": number
    }
  ],
  "escalationTargets": [
    {
      "memberId": "string",
      "memberName": "string",
      "escalationReason": "string",
      "escalationCount": number,
      "shouldEscalate": boolean
    }
  ],
  "escalationMessages": [
    {
      "targetMemberId": "string",
      "messageType": "email" | "chat",
      "messageContent": "string"
    }
  ],
  "executionLog": [
    {
      "timestamp": "string",
      "action": "string",
      "status": "success" | "failure",
      "details": "string"
    }
  ]
}`;

  const userPrompt = `Process the following confirmation email content and execute escalation procedures:

Confirmation Email Content:
${context.confirmationEmailContent}

Reporting Deadline: ${context.reportingDeadline}
Escalation Threshold: ${context.escalationThreshold}
Previous Escalation Counts: ${JSON.stringify(context.previousEscalationCount)}

Please analyze the email content, identify non-reporting members, determine escalation targets, and generate appropriate escalation messages.`;

  return `${systemPrompt}\n\n${userPrompt}`;
}
