// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Tx3Imp1ConfirmationEmailContent {
  recipientId: string;
  recipientName: string;
  recipientEmail: string;
  submissionStatus: "submitted" | "pending" | "overdue";
  submissionTime?: string;
  reportContent?: {
    yesterday: string;
    today: string;
    issues: string;
  };
}

export interface Tx3Imp1PromptContext {
  confirmationEmails: Tx3Imp1ConfirmationEmailContent[];
  currentTimestamp: string;
  submissionDeadline: string;
  escalationThresholdMinutes: number;
}

export interface Tx3Imp1IdentifiedMember {
  memberId: string;
  memberName: string;
  memberEmail: string;
  status: "not_reported" | "delayed" | "submitted";
  daysSinceDeadline?: number;
  previousEscalationCount: number;
}

export interface Tx3Imp1Action02Output {
  identifiedMembers: Tx3Imp1IdentifiedMember[];
  escalationTargets: Tx3Imp1IdentifiedMember[];
  totalAnalyzed: number;
  totalNotReported: number;
  totalDelayed: number;
  analysisTimestamp: string;
}

export function buildAction02Prompt(
  context: Tx3Imp1PromptContext
): string {
  const emailSummary = context.confirmationEmails
    .map(
      (email) =>
        `- ${email.recipientName} (${email.recipientEmail}): ${email.submissionStatus}`
    )
    .join("\n");

  const prompt = `You are an AI agent responsible for identifying non-reporting and delayed members from confirmation email data.

Current timestamp: ${context.currentTimestamp}
Submission deadline: ${context.submissionDeadline}
Escalation threshold: ${context.escalationThresholdMinutes} minutes after deadline

Confirmation email data:
${emailSummary}

Your task:
1. Analyze each confirmation email entry
2. Identify members with "pending" or "overdue" status
3. Determine escalation targets based on:
   - Status is "overdue"
   - Time since deadline exceeds escalation threshold
   - Previous escalation count should be considered for repeat offenders
4. Classify each member as "not_reported", "delayed", or "submitted"
5. Calculate days since deadline for delayed members

Return a structured analysis with:
- List of identified non-reporting and delayed members
- List of escalation targets (subset of identified members)
- Summary counts
- Analysis timestamp

Focus on accuracy and completeness in member identification.`;

  return prompt;
}
