// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01PromptInput {
  confirmationEmailContent: string;
  reportDeadline: string;
  currentTimestamp: string;
  teamMembers: Array<{
    id: string;
    name: string;
    email: string;
  }>;
}

export interface Action01PromptOutput {
  unreportedMembers: Array<{
    id: string;
    name: string;
    email: string;
    reason: "not_submitted" | "delayed";
  }>;
  analysisTimestamp: string;
}

export function buildAction01Prompt(input: Action01PromptInput): string {
  const membersList = input.teamMembers
    .map((member) => `- ${member.name} (${member.email})`)
    .join("\n");

  return `You are an AI agent responsible for identifying unreported and delayed team members from confirmation email content.

## Task
Analyze the confirmation email content and identify which team members have not submitted their daily reports or have submitted them late.

## Input Information
- Confirmation Email Content:
${input.confirmationEmailContent}

- Report Deadline: ${input.reportDeadline}
- Current Timestamp: ${input.currentTimestamp}
- Team Members:
${membersList}

## Instructions
1. Parse the confirmation email content to extract submitted reports
2. Compare submitted reports against the complete team member list
3. Identify members who have not submitted reports (not_submitted)
4. Identify members whose reports were submitted after the deadline (delayed)
5. For each unreported or delayed member, provide their ID, name, email, and reason

## Output Format
Return a JSON object with the following structure:
{
  "unreportedMembers": [
    {
      "id": "member_id",
      "name": "member_name",
      "email": "member_email",
      "reason": "not_submitted" | "delayed"
    }
  ],
  "analysisTimestamp": "ISO8601_timestamp"
}

## Important Notes
- Be precise in identifying unreported members
- Distinguish between not_submitted and delayed cases
- Include all relevant member information
- Use ISO8601 format for timestamps`;
}
