// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Tx3Imp1ConfirmationEmailContent {
  emailId: string;
  sentAt: string;
  recipientEmail: string;
  recipientName: string;
  subject: string;
  body: string;
  reportedMembers: Array<{
    memberId: string;
    memberName: string;
    status: "submitted" | "pending" | "overdue";
    submittedAt?: string;
  }>;
}

export interface Tx3Imp1PromptContext {
  confirmationEmailContent: Tx3Imp1ConfirmationEmailContent;
  currentTimestamp: string;
  submissionDeadline: string;
  escalationThresholdMinutes: number;
}

export interface Tx3Imp1IdentifiedMember {
  memberId: string;
  memberName: string;
  memberEmail: string;
  status: "not_submitted" | "overdue" | "submitted";
  hoursOverdue?: number;
  lastReminderSentAt?: string;
  reminderCount: number;
}

export interface Tx3Imp1Action02Output {
  identifiedMembers: Tx3Imp1IdentifiedMember[];
  totalIdentified: number;
  notSubmittedCount: number;
  overdueCount: number;
  submittedCount: number;
  analysisTimestamp: string;
}

export function buildAction02Prompt(context: Tx3Imp1PromptContext): string {
  const {
    confirmationEmailContent,
    currentTimestamp,
    submissionDeadline,
    escalationThresholdMinutes,
  } = context;

  const reportedMembersText = confirmationEmailContent.reportedMembers
    .map(
      (member) =>
        `- ${member.memberName} (ID: ${member.memberId}): ${member.status}${member.submittedAt ? ` at ${member.submittedAt}` : ""}`
    )
    .join("\n");

  return `You are an AI agent responsible for identifying members with missing or overdue reports from confirmation email content.

## Task: Identify Missing and Overdue Report Members

### Confirmation Email Content:
- Email ID: ${confirmationEmailContent.emailId}
- Sent At: ${confirmationEmailContent.sentAt}
- Recipient: ${confirmationEmailContent.recipientName} (${confirmationEmailContent.recipientEmail})
- Subject: ${confirmationEmailContent.subject}

### Reported Members Status:
${reportedMembersText}

### Current Context:
- Current Timestamp: ${currentTimestamp}
- Submission Deadline: ${submissionDeadline}
- Escalation Threshold: ${escalationThresholdMinutes} minutes after deadline

## Analysis Instructions:

1. **Identify Not Submitted Members**: Extract all members with status "pending" or "not_submitted"
2. **Identify Overdue Members**: Extract all members whose submission is past the deadline
3. **Calculate Overdue Duration**: For overdue members, calculate hours past the deadline
4. **Track Reminder History**: Note if previous reminders have been sent to each member
5. **Classify by Escalation Level**: Determine if member requires immediate escalation based on threshold

## Output Format:

Provide a JSON response with the following structure:
{
  "identifiedMembers": [
    {
      "memberId": "string",
      "memberName": "string",
      "memberEmail": "string",
      "status": "not_submitted" | "overdue" | "submitted",
      "hoursOverdue": number (optional, only for overdue),
      "lastReminderSentAt": "string" (optional, ISO timestamp),
      "reminderCount": number
    }
  ],
  "totalIdentified": number,
  "notSubmittedCount": number,
  "overdueCount": number,
  "submittedCount": number,
  "analysisTimestamp": "${currentTimestamp}"
}

## Important Notes:
- Only include members with status "not_submitted" or "overdue" in the identifiedMembers array
- Calculate hoursOverdue as the difference between currentTimestamp and submissionDeadline
- reminderCount should reflect the number of previous reminders sent to each member
- Ensure all timestamps are in ISO 8601 format
- Be precise in member identification to avoid sending reminders to already-submitted members`;
}
