// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-3-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptInput {
  confirmationEmailContent: string;
  reportingDeadline: string;
  currentTimestamp: string;
  previousReminders: Array<{
    employeeId: string;
    reminderCount: number;
    lastReminderTime: string;
  }>;
  reminderRules: {
    maxReminderCount: number;
    reminderIntervalMinutes: number;
  };
}

export interface Action04PromptOutput {
  identifiedNonReporters: Array<{
    employeeId: string;
    employeeName: string;
    reason: "not_submitted" | "delayed";
    daysSinceDeadline: number;
  }>;
  remindersToSend: Array<{
    employeeId: string;
    employeeName: string;
    reminderCount: number;
    shouldSendEmail: boolean;
    shouldSendChat: boolean;
    message: string;
  }>;
  escalationCases: Array<{
    employeeId: string;
    employeeName: string;
    reason: string;
    requiresHumanReview: boolean;
  }>;
  sendingLog: Array<{
    employeeId: string;
    channel: "email" | "chat";
    timestamp: string;
    status: "pending" | "sent" | "failed";
    messageId?: string;
  }>;
}

export function buildAction04Prompt(input: Action04PromptInput): string {
  const reminderRulesText = `
催促ルール:
- 最大催促回数: ${input.reminderRules.maxReminderCount}回
- 催促間隔: ${input.reminderRules.reminderIntervalMinutes}分
`;

  const previousRemindersText =
    input.previousReminders.length > 0
      ? `
前回の催促履歴:
${input.previousReminders
  .map(
    (r) =>
      `- 従業員ID: ${r.employeeId}, 催促回数: ${r.reminderCount}回, 最終催促時刻: ${r.lastReminderTime}`
  )
  .join("\n")}
`
      : "前回の催促履歴: なし";

  return `あなたは朝会報告管理システムのAIエージェントです。確認メール内容から報告漏れ・遅延部員を特定し、催促対象を判定してメール・チャットを送信します。

【現在の状況】
確認メール内容:
${input.confirmationEmailContent}

報告期限: ${input.reportingDeadline}
現在時刻: ${input.currentTimestamp}

${reminderRulesText}

${previousRemindersText}

【あなたのタスク】
1. 確認メール内容から報告漏れ・遅延部員を特定してください
2. 催促対象部員を判定してください（催促ルールに基づいて）
3. 各部員に対して送信すべき催促メール・チャットを決定してください
4. 送信結果をログに記録してください
5. 複数回催促後も報告がない場合や特殊ケースはエスカレーション対象として特定してください

【出力形式】
以下のJSON形式で結果を返してください:
{
  "identifiedNonReporters": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "reason": "not_submitted" | "delayed",
      "daysSinceDeadline": number
    }
  ],
  "remindersToSend": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "reminderCount": number,
      "shouldSendEmail": boolean,
      "shouldSendChat": boolean,
      "message": "string"
    }
  ],
  "escalationCases": [
    {
      "employeeId": "string",
      "employeeName": "string",
      "reason": "string",
      "requiresHumanReview": boolean
    }
  ],
  "sendingLog": [
    {
      "employeeId": "string",
      "channel": "email" | "chat",
      "timestamp": "string",
      "status": "pending" | "sent" | "failed",
      "messageId": "string (optional)"
    }
  ]
}

【注意事項】
- 催促回数が上限に達した場合はエスカレーション対象にしてください
- 同一部員への過度な催促を避けてください
- 送信履歴は正確に記録してください
- 特殊ケースや判定が困難な場合は人間レビューが必要と判定してください`;
}
