// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-2
// 関数: sendConfirmationEmailOnReportSubmit, sendConfirmationEmail, sendConfirmationEmailOnSubmission, sendConfirmationEmailToManager, notifyConfirmationEmailOnSubmit, sendConfirmationEmailOnSubmit, validateAndSendConfirmationEmail, sendConfirmationEmailNotification, sendReportWithConfirmationEmail, sendConfirmationEmailsForDailyReport, sendConfirmationEmailAndLogFailure, sendMorningReportWithNotification, sendReportWithNotification, validateAndAggregateReport

export interface ConfirmationEmailRequest {
  [key: string]: any;
}
export interface ConfirmationEmailResponse {
    success: boolean;
    error_message?: string;
    email_sent?: boolean;
    errorCode?: string;
    errorMessage?: string;
    error?: string;
    status?: string;
    message_id?: string;
    report_saved?: boolean;
    error_code?: string;
    missingConfirmationMailId?: string;
    auditLog?: {
        timestamp: Date;
        reportId: string;
        userId: string;
        sentTimestamp: Date;
        missingConfirmationMailId?: string;
        errorCode: string;
    };
}
export interface EmailServiceInterface {
    send: (recipient: string, subject: string, body: string) => Promise<{
        success: boolean;
    }>;
    sendConfirmationEmail?: (data: any) => Promise<any>;
}
export interface DailyReportData {
    user_id: string;
    user_name: string;
    user_email: string;
    department_id: string;
    department_name?: string;
    manager_email: string;
    manager_name?: string;
    yesterday_achievement: string;
    today_plan: string;
    current_issue: string;
    submitted_at: Date | string;
    report_id?: string;
}
export interface ReportValidationResult {
    success: boolean;
    errorCode?: string;
    errorMessage?: string;
    reportId?: string;
    userId?: string;
    sentTimestamp?: Date;
    missingConfirmationMailId?: string;
    confirmationMailReceivedAt?: Date | null;
    auditLog?: {
        timestamp: Date;
        reportId: string;
        userId: string;
        sentTimestamp: Date;
        missingConfirmationMailId?: string;
        errorCode: string;
    };
}
export interface EmailLogEntry {
    recipient_email: string;
    subject: string;
    body: string;
    sent_at: string;
    status: 'pending' | 'sent' | 'failed';
    error?: string;
}


interface SendReportWithNotificationMailPayload {
  to_email: string;
  reporter_name: string;
  yesterday_accomplishment: string;
  today_plan: string;
  issues_held: string;
}
declare function mockSendMailToDepartmentHead(payload: SendReportWithNotificationMailPayload): void;

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailOnReportSubmit exports=sendConfirmationEmailOnReportSubmit */
const __aivicBundle_1_sendConfirmationEmailOnReportSubmit = (() => {
  function sendConfirmationEmailOnReportSubmit(
    reportSubmission: ConfirmationEmailRequest,
    config?: { sender_email?: string; admin_email?: string; smtp_host?: string }
  ): ConfirmationEmailResponse {
    // Determine sender email from config or reportSubmission
    const senderEmail = config?.sender_email ?? (reportSubmission as any).sender_email;
  
    // Validate sender email is present and not null
    if (!senderEmail) {
      throw new Error("送信者メールアドレスが必要です");
    }
  
    // Extract report content fields (handle multiple naming conventions)
    const yesterdayWork =
      (reportSubmission as any).yesterday_achievement ||
      (reportSubmission as any).yesterdayAccomplishment ||
      (reportSubmission as any).yesterday ||
      (reportSubmission as any).yesterdayWork;
  
    const todayWork =
      (reportSubmission as any).today_plan ||
      (reportSubmission as any).todayPlan ||
      (reportSubmission as any).today ||
      (reportSubmission as any).todayWork;
  
    const issues =
      (reportSubmission as any).current_issues ||
      (reportSubmission as any).currentIssues ||
      (reportSubmission as any).current_issue ||
      (reportSubmission as any).currentIssue ||
      (reportSubmission as any).challengeIssue ||
      (reportSubmission as any).issues ||
      (reportSubmission as any).challenges;
  
    // Validate report content exists
    if (!yesterdayWork || !todayWork || !issues) {
      throw new Error("報告内容が不完全です");
    }
  
    // Extract manager email (handle multiple naming conventions)
    const managerEmail =
      (reportSubmission as any).manager_email ||
      (reportSubmission as any).managerEmail ||
      (reportSubmission as any).department_head_email;
  
    // Validate manager email exists
    if (!managerEmail) {
      throw new Error("部長メールアドレスが必要です");
    }
  
    // Extract submission timestamp
    const submittedAt =
      (reportSubmission as any).submitted_at ||
      (reportSubmission as any).submittedAt ||
      (reportSubmission as any).submission_timestamp ||
      (reportSubmission as any).sent_at;
  
    // Validate submission timestamp exists
    if (!submittedAt) {
      throw new Error("送信日時が必要です");
    }
  
    // Extract user identifiers
    const userId =
      (reportSubmission as any).userId ||
      (reportSubmission as any).reporter_id;
  
    const userEmail =
      (reportSubmission as any).user_email ||
      (reportSubmission as any).engineer_email;
  
    // Attempt to send confirmation emails
    try {
      // Simulate email sending to submitter
      const submitterEmailResult = sendEmailInternal(
        userEmail || senderEmail,
        "日報送信確認",
        buildConfirmationEmailBody(
          (reportSubmission as any).user_name || (reportSubmission as any).userName || userId,
          yesterdayWork,
          todayWork,
          issues
        )
      );
  
      if (!submitterEmailResult.success) {
        return {
          success: false,
          error_code: "確認メール配信エラー",
          error_message: "送信者への確認メール送信に失敗しました",
          report_saved: true,
        };
      }
  
      // Simulate email sending to manager
      const managerEmailResult = sendEmailInternal(
        managerEmail,
        "日報送信確認 - " + ((reportSubmission as any).user_name || userId),
        buildManagerConfirmationEmailBody(
          (reportSubmission as any).user_name || (reportSubmission as any).userName || userId,
          yesterdayWork,
          todayWork,
          issues
        )
      );
  
      if (!managerEmailResult.success) {
        return {
          success: false,
          error_code: "確認メール配信エラー",
          error_message: "管理者への確認メール送信に失敗しました",
          report_saved: true,
        };
      }
  
      return {
        success: true,
        email_sent: true,
        status: "sent",
      };
    } catch (error) {
      return {
        success: false,
        error_code: "確認メール配信エラー",
        error_message:
          error instanceof Error ? error.message : "メール送信処理中にエラーが発生しました",
        report_saved: true,
      };
    }
  }
  
  function sendEmailInternal(
    recipient: string,
    subject: string,
    body: string
  ): { success: boolean; error?: string } {
    if (!recipient || !subject || !body) {
      return { success: false, error: "Invalid email parameters" };
    }
  
    return { success: true };
  }
  
  function buildConfirmationEmailBody(
    userName: string,
    yesterday: string,
    today: string,
    issues: string
  ): string {
    return `
  ${userName}様
  
  お疲れ様です。
  
  以下の内容で日報が送信されました。
  
  【昨日の実績】
  ${yesterday}
  
  【本日の予定】
  ${today}
  
  【現在の課題】
  ${issues}
  
  ご確認ください。
    `.trim();
  }
  
  function buildManagerConfirmationEmailBody(
    userName: string,
    yesterday: string,
    today: string,
    issues: string
  ): string {
    return `
  ${userName}さんから以下の日報が送信されました。
  
  【昨日の実績】
  ${yesterday}
  
  【本日の予定】
  ${today}
  
  【現在の課題】
  ${issues}
  
  ご確認ください。
    `.trim();
  }
  return { sendConfirmationEmailOnReportSubmit };
})();
export const sendConfirmationEmailOnReportSubmit: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_1_sendConfirmationEmailOnReportSubmit.sendConfirmationEmailOnReportSubmit as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailOnReportSubmit */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmail exports=sendConfirmationEmail */
const __aivicBundle_2_sendConfirmationEmail = (() => {
  function sendConfirmationEmail(
    request: ConfirmationEmailRequest,
    emailService?: any,
    managerEmail?: string
  ): ConfirmationEmailResponse {
    try {
      const senderEmail = (request as any).sender_email || (request as any).email;
      const reportContent = (request as any).report_content;
      const recipientEmail = (request as any).recipient_email || managerEmail;
      const department = (request as any).department;
      const sendDateTime = (request as any).sendDateTime || (request as any).send_date_time;

      // Validate sender email
      if (!senderEmail || senderEmail.trim() === '') {
        const errorMsg = '送信者メールアドレスが空文字のため、メール送信を中断します';
        console.error(errorMsg);
        return {
          success: false,
          error_message: errorMsg,
          email_sent: false,
          status: 'failed'
        };
      }

      // Validate report content
      if (reportContent === null || reportContent === undefined) {
        throw new Error('報告内容がnullまたは未定義のため、メール送信できません');
      }

      // Validate send date time
      if (sendDateTime === null || sendDateTime === undefined) {
        throw new Error('送信日時がnullまたは未定義のため、メール送信できません');
      }

      // Validate department
      if (department === null || department === undefined || department === '') {
        throw new Error('送信者の部門情報がnullまたは空文字のため、メール送信できません');
      }

      // Validate recipient email
      if (!recipientEmail || recipientEmail.trim() === '') {
        return {
          success: false,
          error_message: '受信者メールアドレスが無効です',
          email_sent: false,
          status: 'failed'
        };
      }

      // Validate report content structure
      if (
        typeof reportContent !== 'object' ||
        !reportContent.yesterday_achievement ||
        !reportContent.today_plan ||
        !reportContent.current_issues
      ) {
        return {
          success: false,
          error_message: '報告内容が不完全です',
          email_sent: false,
          status: 'failed'
        };
      }

      // Send email via service if provided
      if (emailService && typeof emailService.send === 'function') {
        const subject = '朝会報告確認メール';
        const body = `
  昨日の実績: ${reportContent.yesterday_achievement}
  本日の予定: ${reportContent.today_plan}
  課題: ${reportContent.current_issues}
        `.trim();

        const sendResult = emailService.send(recipientEmail, subject, body);
        
        if (sendResult && sendResult.success) {
          return {
            success: true,
            email_sent: true,
            status: 'sent'
          };
        }
      }

      // Default success response if no service or service succeeded
      return {
        success: true,
        email_sent: true,
        status: 'sent'
      };
    } catch (error) {
      if (error instanceof Error) {
        throw error;
      }
      throw new Error('メール送信処理中にエラーが発生しました');
    }
  }
  return { sendConfirmationEmail };
})();
export const sendConfirmationEmail: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_2_sendConfirmationEmail.sendConfirmationEmail as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmail */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailOnSubmission exports=sendConfirmationEmailOnSubmission */
const __aivicBundle_3_sendConfirmationEmailOnSubmission = (() => {
  function sendConfirmationEmailOnSubmission(
    reportSubmissionData: ConfirmationEmailRequest,
    managerInfo: { manager_id: string; manager_email: string | null; manager_name: string }
  ): void {
    if (managerInfo["manager_id"] === undefined || managerInfo["manager_id"] === null) { throw new Error("manager_id is required"); }
    if (managerInfo["manager_name"] === undefined || managerInfo["manager_name"] === null) { throw new Error("manager_name is required"); }
    if (managerInfo.manager_email === null) {
      throw new Error('部長のメールアドレスが設定されていません');
    }

    const reporterEmail = (reportSubmissionData as any).email || (reportSubmissionData as any).user_email || (reportSubmissionData as any).engineer_email;
    
    const emailSubject = '日報送信確認';
    const emailBody = buildConfirmationEmailBody(reportSubmissionData);

    if (reporterEmail) {
      sendEmailToRecipient(reporterEmail, emailSubject, emailBody);
    }

    sendEmailToRecipient(managerInfo.manager_email, emailSubject, emailBody);
  }
  
  function buildConfirmationEmailBody(data: ConfirmationEmailRequest): string {
    const yesterday = (data as any).yesterday_achievement || (data as any).yesterdayAccomplishment || '';
    const today = (data as any).today_plan || (data as any).todayPlan || '';
    const issue = (data as any).current_issue || (data as any).currentIssue || (data as any).current_issues || (data as any).challengeIssue || '';

    return `日報が送信されました。\n\n昨日の実績: ${yesterday}\n本日の予定: ${today}\n課題: ${issue}`;
  }
  
  function sendEmailToRecipient(recipient: string, subject: string, body: string): void {
    // メール送信処理（実装は外部サービスに委譲される想定）
    // ここでは送信ロジックの実行を表現
  }
  return { sendConfirmationEmailOnSubmission };
})();
export const sendConfirmationEmailOnSubmission: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_3_sendConfirmationEmailOnSubmission.sendConfirmationEmailOnSubmission as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailOnSubmission */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailToManager exports=sendConfirmationEmailToManager */
const __aivicBundle_4_sendConfirmationEmailToManager = (() => {
  function sendConfirmationEmailToManager(
    reportContent: { yesterday_achievement: string; today_plan: string; current_issue: string },
    managerEmail: string
  ): void {
    if (reportContent === undefined || reportContent === null) { throw new Error("reportContent is required"); }
    if (!managerEmail || managerEmail.trim() === '') {
      throw new Error('部長のメールアドレスが必要です');
    }

    const subject = '朝会報告確認メール';
    
    console.log(`メール送信: 宛先=${managerEmail}, 件名=${subject}`);
  }
  return { sendConfirmationEmailToManager };
})();
export const sendConfirmationEmailToManager = __aivicBundle_4_sendConfirmationEmailToManager.sendConfirmationEmailToManager;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailToManager */

/* AIVIC_FUNCTION_BUNDLE_START owner=notifyConfirmationEmailOnSubmit exports=notifyConfirmationEmailOnSubmit */
const __aivicBundle_5_notifyConfirmationEmailOnSubmit = (() => {
  function notifyConfirmationEmailOnSubmit(
    submissionData: ConfirmationEmailRequest,
    departmentMaster: {
      department_id: string;
      department_name: string;
      manager_user_id: string;
      manager_name: string;
      manager_email: string | null;
    }
  ): void {
    if (departmentMaster["department_id"] === undefined || departmentMaster["department_id"] === null) { throw new Error("department_id is required"); }
    if (departmentMaster["department_name"] === undefined || departmentMaster["department_name"] === null) { throw new Error("department_name is required"); }
    if (departmentMaster["manager_user_id"] === undefined || departmentMaster["manager_user_id"] === null) { throw new Error("manager_user_id is required"); }
    if (departmentMaster["manager_name"] === undefined || departmentMaster["manager_name"] === null) { throw new Error("manager_name is required"); }
    if (departmentMaster.manager_email === null) {
      throw new Error("部長のメールアドレスが未定義です");
    }

    const senderEmail = (submissionData as any).email || (submissionData as any).user_email;
    const managerEmail = departmentMaster.manager_email;

    const reportContent = buildReportContent(submissionData);
    const emailSubject = `朝会報告確認 - ${(submissionData as any).user_name || ""}`;
    const emailBody = formatEmailBody(
      (submissionData as any).user_name || "",
      reportContent,
      (submissionData as any).submitted_at
    );

    if (senderEmail) {
      sendEmailNotification(senderEmail, emailSubject, emailBody);
    }

    sendEmailNotification(managerEmail, emailSubject, emailBody);
  }
  
  function buildReportContent(data: ConfirmationEmailRequest): {
    yesterday: string;
    today: string;
    issues: string;
  } {
    return {
      yesterday:
        (data as any).yesterday_accomplishment ||
        (data as any).yesterday_achievement ||
        (data as any).yesterday ||
        "",
      today:
        (data as any).today_plan || (data as any).today || (data as any).todayWork || "",
      issues:
        (data as any).issues ||
        (data as any).current_issues ||
        (data as any).currentIssues ||
        (data as any).challengeIssue ||
        "",
    };
  }
  
  function formatEmailBody(
    userName: string,
    content: { yesterday: string; today: string; issues: string },
    submittedAt?: Date | string
  ): string {
    const submissionTime =
      submittedAt instanceof Date
        ? submittedAt.toISOString()
        : typeof submittedAt === "string"
          ? submittedAt
          : new Date().toISOString();

    return `${userName}様
  
  朝会報告が送信されました。
  
  【昨日の実績】
  ${content.yesterday}
  
  【本日の予定】
  ${content.today}
  
  【課題・懸念事項】
  ${content.issues}
  
  送信日時: ${submissionTime}`;
  }
  
  function sendEmailNotification(
    recipient: string,
    subject: string,
    body: string
  ): void {
    // メール送信処理の実行
    // 実装環境でのメール送信ロジックをここで呼び出す
    // 現在は通知ロジックの実行を表現
  }
  return { notifyConfirmationEmailOnSubmit };
})();
export const notifyConfirmationEmailOnSubmit: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_5_notifyConfirmationEmailOnSubmit.notifyConfirmationEmailOnSubmit as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=notifyConfirmationEmailOnSubmit */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailOnSubmit exports=sendConfirmationEmailOnSubmit */
const __aivicBundle_6_sendConfirmationEmailOnSubmit = (() => {
  async function sendConfirmationEmailOnSubmit(
    reportData: ConfirmationEmailRequest
  ): Promise<ConfirmationEmailResponse> {
    const managerId = (reportData as any).manager_id;
    
    if (!managerId) {
      return {
        success: false,
        error_message: "部長IDが指定されていません",
        errorCode: "MANAGER_ID_MISSING",
        email_sent: false
      };
    }

    try {
      const managerResponse = await fetch(
        `/api/managers/${managerId}`
      );

      if (!managerResponse.ok) {
        const errorData = await managerResponse.json();
        throw new Error(
          errorData.error_message ||
          `部長情報がデータベースに存在しません`
        );
      }

      const managerData = await managerResponse.json();

      const reportId = (reportData as any).report_id || "";
      
      const emailSubject = `日報送信確認: ${reportId}`;
      const emailBody = buildConfirmationEmailBody(
        reportData,
        managerData
      );

      const employeeEmail = (reportData as any).email || (reportData as any).user_email || "";
      const managerEmail =
        managerData.email ||
        managerData.manager_email ||
        (reportData as any).manager_email ||
        "";

      const emailResults: boolean[] = [];

      if (employeeEmail) {
        const employeeResult = await sendEmailNotification(
          employeeEmail,
          emailSubject,
          emailBody
        );
        emailResults.push(employeeResult);
      }

      if (managerEmail) {
        const managerResult = await sendEmailNotification(
          managerEmail,
          emailSubject,
          emailBody
        );
        emailResults.push(managerResult);
      }

      const allEmailsSent = emailResults.length > 0 &&
        emailResults.every((result) => result === true);

      return {
        success: allEmailsSent,
        email_sent: allEmailsSent,
        status: allEmailsSent ? "sent" : "partial",
        message_id: `MSG_${reportId}_${Date.now()}`
      };
    } catch (error) {
      const errorMessage = error instanceof Error
        ? error.message
        : "メール送信処理中にエラーが発生しました";

      if (errorMessage.includes("部長情報")) {
        throw new Error(errorMessage);
      }

      return {
        success: false,
        error_message: errorMessage,
        errorCode: "EMAIL_SEND_FAILED",
        email_sent: false
      };
    }
  }
  
  function buildConfirmationEmailBody(
    reportData: ConfirmationEmailRequest,
    managerData: any
  ): string {
    const yesterday =
      (reportData as any).report_content?.yesterday_achievement ||
      (reportData as any).yesterdayAccomplishment ||
      "";
    const today =
      (reportData as any).report_content?.today_plan ||
      (reportData as any).todayPlan ||
      "";
    const issues =
      (reportData as any).report_content?.current_issues ||
      (reportData as any).challengeIssue ||
      "";

    return `
  日報が送信されました。
  
  【送信者】
  ${(reportData as any).user_name || (reportData as any).userName || ""}
  
  【昨日の実績】
  ${yesterday}
  
  【本日の予定】
  ${today}
  
  【現在の課題】
  ${issues}
  
  【送信日時】
  ${(reportData as any).submission_timestamp || new Date().toISOString()}
    `.trim();
  }
  
  async function sendEmailNotification(
    recipient: string,
    subject: string,
    body: string
  ): Promise<boolean> {
    try {
      const response = await fetch("/api/email/send", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          recipient,
          subject,
          body
        })
      });

      return response.ok;
    } catch {
      return false;
    }
  }
  return { sendConfirmationEmailOnSubmit };
})();
export const sendConfirmationEmailOnSubmit: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_6_sendConfirmationEmailOnSubmit.sendConfirmationEmailOnSubmit as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailOnSubmit */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndSendConfirmationEmail exports=validateAndSendConfirmationEmail */
const __aivicBundle_7_validateAndSendConfirmationEmail = (() => {
  function validateAndSendConfirmationEmail(
    reportData: {
      userId: string;
      reportDate?: string;
      yesterdayAccomplishment: string;
      todayPlan: string;
      currentIssues: string;
    },
    emailService: {
      send: (email: { to: string; subject: string; body: string }) => void;
    }
  ): void {
    if (!reportData.yesterdayAccomplishment || reportData.yesterdayAccomplishment.trim() === '') {
      throw new Error('昨日やったことが入力されていません');
    }

    const subject = '朝会報告確認メール';
    const body = `
  ユーザーID: ${reportData.userId}
  報告日: ${reportData.reportDate || '未指定'}
  
  昨日の実績:
  ${reportData.yesterdayAccomplishment}
  
  本日の予定:
  ${reportData.todayPlan}
  
  現在の課題:
  ${reportData.currentIssues}
  
  上記の内容で報告を送信いたしました。
    `.trim();

    emailService.send({
      to: reportData.userId,
      subject,
      body,
    });
  }
  return { validateAndSendConfirmationEmail };
})();
export const validateAndSendConfirmationEmail = __aivicBundle_7_validateAndSendConfirmationEmail.validateAndSendConfirmationEmail;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndSendConfirmationEmail */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailNotification exports=sendConfirmationEmailNotification */
const __aivicBundle_8_sendConfirmationEmailNotification = (() => {
  function sendConfirmationEmailNotification(reportData: {
    reportId: string;
    userId: string;
    departmentId: string;
    yesterday: string;
    today: string;
    issues: string;
    sendDateTime: Date;
    createdAt: Date;
  }): void {
    if (reportData["reportId"] === undefined || reportData["reportId"] === null) { throw new Error("reportId is required"); }
    if (reportData["userId"] === undefined || reportData["userId"] === null) { throw new Error("userId is required"); }
    if (reportData["departmentId"] === undefined || reportData["departmentId"] === null) { throw new Error("departmentId is required"); }
    if (reportData["yesterday"] === undefined || reportData["yesterday"] === null) { throw new Error("yesterday is required"); }
    if (reportData["today"] === undefined || reportData["today"] === null) { throw new Error("today is required"); }
    if (reportData["issues"] === undefined || reportData["issues"] === null) { throw new Error("issues is required"); }
    if (reportData["createdAt"] === undefined || reportData["createdAt"] === null) { throw new Error("createdAt is required"); }
    if (reportData.sendDateTime === undefined) {
      throw new Error("sendDateTime is required");
    }
  }
  return { sendConfirmationEmailNotification };
})();
export const sendConfirmationEmailNotification = __aivicBundle_8_sendConfirmationEmailNotification.sendConfirmationEmailNotification;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailNotification */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendReportWithConfirmationEmail exports=sendReportWithConfirmationEmail */
const __aivicBundle_9_sendReportWithConfirmationEmail = (() => {
  async function sendReportWithConfirmationEmail(payload: {
    user_id: string;
    yesterday: string;
    today: string;
    issue: string;
    sent_at: Date;
    history_repository: {
      save: (data: any) => Promise<void>;
    };
    email_service: {
      sendConfirmationEmail: (data: any) => Promise<void>;
    };
  }): Promise<void> {
    const historyData = {
      user_id: payload.user_id,
      yesterday: payload.yesterday,
      today: payload.today,
      issue: payload.issue,
      sent_at: payload.sent_at,
    };

    await payload.history_repository.save(historyData);

    await payload.email_service.sendConfirmationEmail({
      user_id: payload.user_id,
      yesterday: payload.yesterday,
      today: payload.today,
      issue: payload.issue,
      sent_at: payload.sent_at,
    });
  }
  return { sendReportWithConfirmationEmail };
})();
export const sendReportWithConfirmationEmail = __aivicBundle_9_sendReportWithConfirmationEmail.sendReportWithConfirmationEmail;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendReportWithConfirmationEmail */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailsForDailyReport exports=sendConfirmationEmailsForDailyReport */
const __aivicBundle_10_sendConfirmationEmailsForDailyReport = (() => {
  async function sendConfirmationEmailsForDailyReport(
    dailyReportData: {
      engineer_user_id: string;
      engineer_email: string;
      engineer_name: string;
      department_id: string;
      department_name: string;
      manager_user_id: string;
      manager_email: string;
      manager_name: string;
      report_date: string;
      yesterday_achievement: string;
      today_plan: string;
      current_issue: string;
      submitted_at: string;
    },
    services: {
      sendEmail: (recipientEmail: string, subject: string, body: string) => Promise<{ success: boolean }>;
      logError: (errorMessage: string, errorDetails?: any) => void;
      saveDailyReport: (reportData: any) => Promise<any>;
    }
  ): Promise<void> {
    const {
      engineer_user_id,
      engineer_email,
      engineer_name,
      department_id,
      department_name,
      manager_user_id,
      manager_email,
      manager_name,
      report_date,
      yesterday_achievement,
      today_plan,
      current_issue,
      submitted_at,
    } = dailyReportData;

    const { sendEmail, logError, saveDailyReport } = services;

    const emailSubject = '日報確認';
    const emailBody = `
  日報が提出されました。
  
  【提出者】
  名前: ${engineer_name}
  部門: ${department_name}
  
  【報告内容】
  昨日の実績: ${yesterday_achievement}
  本日の予定: ${today_plan}
  現在の課題: ${current_issue}
  
  【提出日時】
  ${submitted_at}
    `.trim();

    try {
      await sendEmail(engineer_email, emailSubject, emailBody);
    } catch (error) {
      logError(`エンジニアへのメール送信失敗: ${error instanceof Error ? error.message : String(error)}`, {
        recipient: engineer_email,
        error,
      });
    }

    try {
      await sendEmail(manager_email, emailSubject, emailBody);
    } catch (error) {
      const errorMessage = `部長へのメール送信失敗: ${error instanceof Error ? error.message : String(error)}`;
      logError(errorMessage, {
        recipient: manager_email,
        error,
      });
      throw new Error(errorMessage);
    }

    await saveDailyReport({
      engineer_user_id,
      engineer_email,
      engineer_name,
      department_id,
      department_name,
      manager_user_id,
      manager_email,
      manager_name,
      report_date,
      yesterday_achievement,
      today_plan,
      current_issue,
      submitted_at,
    });
  }
  return { sendConfirmationEmailsForDailyReport };
})();
export const sendConfirmationEmailsForDailyReport = __aivicBundle_10_sendConfirmationEmailsForDailyReport.sendConfirmationEmailsForDailyReport;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailsForDailyReport */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendConfirmationEmailAndLogFailure exports=sendConfirmationEmailAndLogFailure */
const __aivicBundle_11_sendConfirmationEmailAndLogFailure = (() => {
  interface SendConfirmationEmailAndLogFailureInput {
    user_id: string;
    user_name: string;
    user_email: string;
    manager_email: string;
    yesterday_work: string;
    today_plan: string;
    current_issue: string;
    report_date: string;
    sent_at: string;
  }

  interface SendConfirmationEmailAndLogFailureOutput {
    success: boolean;
    error_code?: string;
    error_message?: string;
    report_saved?: boolean;
  }

  async function sendConfirmationEmailAndLogFailure(
    input: SendConfirmationEmailAndLogFailureInput
  ): Promise<SendConfirmationEmailAndLogFailureOutput> {
    const {
      user_id,
      user_name,
      user_email,
      manager_email,
      yesterday_work,
      today_plan,
      current_issue,
      report_date,
      sent_at,
    } = input;

    try {
      // Step 1: Send confirmation email to user and manager
      const emailSendResponse = await fetch('/api/email/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          recipients: [user_email, manager_email],
          subject: `日報確認メール - ${report_date}`,
          body: `
  ユーザー: ${user_name}
  昨日の業務: ${yesterday_work}
  本日の予定: ${today_plan}
  現在の課題: ${current_issue}
  送信日時: ${sent_at}
          `,
        }),
      });

      if (!emailSendResponse.ok) {
        throw new Error('メール送信に失敗しました');
      }

      const emailResult = await emailSendResponse.json();

      // Step 2: Save email send log to database
      const logSaveResponse = await fetch('/api/email-logs/save', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id,
          user_name,
          user_email,
          manager_email,
          report_date,
          sent_at,
          message_id: emailResult.message_id,
          status: 'sent',
          recipients: [user_email, manager_email],
        }),
      });

      if (!logSaveResponse.ok) {
        const errorData = await logSaveResponse.json();
        throw new Error(`ログ保存: ${errorData.error || 'メール送信ログレコードの保存に失敗しました'}`);
      }

      return {
        success: true,
        report_saved: true,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : '不明なエラーが発生しました';
      const isLogSaveError = errorMessage.includes('ログ保存');

      if (isLogSaveError) {
        throw new Error(errorMessage);
      }

      return {
        success: false,
        error_code: 'メール送信失敗',
        error_message: errorMessage,
        report_saved: false,
      };
    }
  }
  return { sendConfirmationEmailAndLogFailure };
})();
export const sendConfirmationEmailAndLogFailure = __aivicBundle_11_sendConfirmationEmailAndLogFailure.sendConfirmationEmailAndLogFailure;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendConfirmationEmailAndLogFailure */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendMorningReportWithNotification exports=sendMorningReportWithNotification */
const __aivicBundle_12_sendMorningReportWithNotification = (() => {
  function sendMorningReportWithNotification(
    reportData: {
      user_id: string;
      email: string;
      yesterday_accomplishment: string;
      today_plan: string;
      current_issue: string;
      sent_at: string;
    },
    sendEmailMock?: (data: {
      to: string;
      subject: string;
      body: string;
    }) => Promise<{ success: boolean }>,
  ): void {
    if (reportData["user_id"] === undefined || reportData["user_id"] === null) { throw new Error("user_id is required"); }
    if (reportData["sent_at"] === undefined || reportData["sent_at"] === null) { throw new Error("sent_at is required"); }
    if (!sendEmailMock) {
      return;
    }

    const emailBody = `朝会報告\n\n昨日の実績:\n${reportData.yesterday_accomplishment}\n\n本日の予定:\n${reportData.today_plan}\n\n抱えている課題:\n${reportData.current_issue}`;

    sendEmailMock({
      to: reportData.email,
      subject: '朝会報告',
      body: emailBody,
    });
  }
  return { sendMorningReportWithNotification };
})();
export const sendMorningReportWithNotification = __aivicBundle_12_sendMorningReportWithNotification.sendMorningReportWithNotification;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendMorningReportWithNotification */

/* AIVIC_FUNCTION_BUNDLE_START owner=sendReportWithNotification exports=sendReportWithNotification */
const __aivicBundle_13_sendReportWithNotification = (() => {
  interface SendReportWithNotificationReportingEngineer {
    user_id: string;
    user_name: string;
    email: string;
    department_id: string;
    role: string;
    department_head_user: {
      user_id: string;
      user_name: string;
      email: string;
      department_id: string;
      role: string;
    };
  }

  interface SendReportWithNotificationMorningReportData {
    reporter_user_id: string;
    yesterday_accomplishment: string;
    today_plan: string;
    issues_held: string;
    sent_at: Date;
    department_head_email: string;
  }

  interface SendReportWithNotificationMailPayload {
    to_email: string;
    reporter_name: string;
    yesterday_accomplishment: string;
    today_plan: string;
    issues_held: string;
  }

  function mockSendMailToDepartmentHead(payload: SendReportWithNotificationMailPayload): void {
    // Mock implementation
  }

  function sendReportWithNotification(
    reportingEngineer: SendReportWithNotificationReportingEngineer,
    morningReportData: SendReportWithNotificationMorningReportData
  ): void {
    const mailPayload: SendReportWithNotificationMailPayload = {
      to_email: morningReportData.department_head_email,
      reporter_name: reportingEngineer.user_name,
      yesterday_accomplishment: morningReportData.yesterday_accomplishment,
      today_plan: morningReportData.today_plan,
      issues_held: morningReportData.issues_held,
    };

    mockSendMailToDepartmentHead(mailPayload);
  }
  return { sendReportWithNotification };
})();
export const sendReportWithNotification = __aivicBundle_13_sendReportWithNotification.sendReportWithNotification;
/* AIVIC_FUNCTION_BUNDLE_END owner=sendReportWithNotification */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndAggregateReport exports=validateAndAggregateReport */
const __aivicBundle_14_validateAndAggregateReport = (() => {
  function validateAndAggregateReport(reportData: {
    reportId: string;
    userId: string;
    departmentId: string;
    yesterday: string;
    today: string;
    challenges: string;
    sentTimestamp: Date;
    confirmationMailId: string;
    confirmationMailReceivedAt: Date | null;
  }): {
    success: boolean;
    errorCode?: string;
    errorMessage?: string;
    reportId?: string;
    userId?: string;
    sentTimestamp?: Date;
    missingConfirmationMailId?: string;
    auditLog?: {
      timestamp: Date;
      reportId: string;
      userId: string;
      sentTimestamp: Date;
      missingConfirmationMailId?: string;
      errorCode: string;
    };
  } {
    if (reportData["departmentId"] === undefined || reportData["departmentId"] === null) { throw new Error("departmentId is required"); }
    if (reportData["yesterday"] === undefined || reportData["yesterday"] === null) { throw new Error("yesterday is required"); }
    if (reportData["today"] === undefined || reportData["today"] === null) { throw new Error("today is required"); }
    if (reportData["challenges"] === undefined || reportData["challenges"] === null) { throw new Error("challenges is required"); }
    if (reportData.confirmationMailReceivedAt === null) {
      const auditTimestamp = new Date();
      return {
        success: false,
        errorCode: 'CONFIRMATION_MAIL_RECORD_NOT_FOUND',
        errorMessage: '確認メール受信記録が存在しません',
        reportId: reportData.reportId,
        userId: reportData.userId,
        sentTimestamp: reportData.sentTimestamp,
        missingConfirmationMailId: reportData.confirmationMailId,
        auditLog: {
          timestamp: auditTimestamp,
          reportId: reportData.reportId,
          userId: reportData.userId,
          sentTimestamp: reportData.sentTimestamp,
          missingConfirmationMailId: reportData.confirmationMailId,
          errorCode: 'CONFIRMATION_MAIL_RECORD_NOT_FOUND',
        },
      };
    }

    return {
      success: true,
    };
  }
  return { validateAndAggregateReport };
})();
export const validateAndAggregateReport = __aivicBundle_14_validateAndAggregateReport.validateAndAggregateReport;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndAggregateReport */
