// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: tx-3-imp-1
// 関数: runTx3Imp1Agent

export interface FollowUpNotification {
    issuedToManager: boolean;
    escalationFlag: boolean;
    requiresHumanConfirmation: boolean;
    reason: string;
}
export interface MockDbTransaction {
    isOpen: boolean;
    isAborted: boolean;
    records: Array<{
        id: string;
        type: string;
        data: unknown;
    }>;
}
export interface Tx3Imp1AgentResult {
    escalationOccurred: boolean;
    escalationReason: string;
    followUpNotification: FollowUpNotification;
    promotionMailSent: boolean;
    promotionChatSent: boolean;
}
export interface Tx3Imp1AiClient {
    evaluateFollowUpTarget(unreportedEmployees: Array<{
        name: string;
    }>, delayedEmployees: Array<{
        name: string;
    }>): Promise<{
        isSpecialCase: boolean;
        requiresHumanReview: boolean;
        reason: string;
    }>;
}
export interface Tx3Imp1AgentInput {
    unreportedEmployees: Array<{
        name: string;
    }>;
    delayedEmployees: Array<{
        name: string;
    }>;
    aiClient: Tx3Imp1AiClient;
    dbTransaction: MockDbTransaction;
    managerNotificationHandler: (notification: FollowUpNotification) => FollowUpNotification;
}


/* AIVIC_FUNCTION_BUNDLE_START owner=runTx3Imp1Agent exports=runTx3Imp1Agent */
const __aivicBundle_1_runTx3Imp1Agent = (() => {
  async function runTx3Imp1Agent(
    input: Tx3Imp1AgentInput,
    context: Record<string, unknown>
  ): Promise<Tx3Imp1AgentResult> {
    if (context === undefined || context === null) { throw new Error("context is required"); }
    const {
      unreportedEmployees,
      delayedEmployees,
      aiClient,
      dbTransaction,
      managerNotificationHandler
    } = input;
  
    // Evaluate follow-up target using AI client
    const aiEvaluation = await aiClient.evaluateFollowUpTarget(
      unreportedEmployees,
      delayedEmployees
    );
  
    // Check if this is a special case that doesn't match promotion rules
    if (aiEvaluation.isSpecialCase || aiEvaluation.requiresHumanReview) {
      // Abort transaction before any side effects
      dbTransaction.isAborted = true;
  
      // Create follow-up notification for manager
      const followUpNotification: FollowUpNotification = {
        issuedToManager: true,
        escalationFlag: true,
        requiresHumanConfirmation: true,
        reason: 'special_case_not_matching_rules'
      };
  
      // Issue manager notification
      managerNotificationHandler(followUpNotification);
  
      // Record follow-up decision in transaction
      dbTransaction.records.push({
        id: `follow_up_decision_${Date.now()}`,
        type: 'follow_up_decision',
        data: {
          status: 'requires_human_confirmation',
          reason: 'special_case_not_matching_rules',
          unreportedEmployeeCount: unreportedEmployees.length,
          delayedEmployeeCount: delayedEmployees.length
        }
      });
  
      // Record manager escalation notification
      dbTransaction.records.push({
        id: `manager_notification_${Date.now()}`,
        type: 'manager_escalation_notification',
        data: {
          escalationTriggeredAt: new Date().toISOString(),
          requiresManagerReview: true,
          unreportedEmployees: unreportedEmployees.map(e => e.name),
          delayedEmployees: delayedEmployees.map(e => e.name),
          reason: 'special_case_not_matching_rules'
        }
      });
  
      return {
        escalationOccurred: true,
        escalationReason: 'special_case_not_matching_rules',
        followUpNotification,
        promotionMailSent: false,
        promotionChatSent: false
      };
    }
  
    // Standard promotion flow for non-special cases
    const followUpNotification: FollowUpNotification = {
      issuedToManager: false,
      escalationFlag: false,
      requiresHumanConfirmation: false,
      reason: ''
    };
  
    // Send promotion mail
    dbTransaction.records.push({
      id: `promotion_mail_log_${Date.now()}`,
      type: 'promotion_mail_log',
      data: {
        sentAt: new Date().toISOString(),
        targetEmployees: [...unreportedEmployees, ...delayedEmployees].map(
          e => e.name
        ),
        mailType: 'follow_up_reminder'
      }
    });
  
    // Send promotion chat
    dbTransaction.records.push({
      id: `promotion_chat_log_${Date.now()}`,
      type: 'promotion_chat_log',
      data: {
        sentAt: new Date().toISOString(),
        targetEmployees: [...unreportedEmployees, ...delayedEmployees].map(
          e => e.name
        ),
        chatType: 'follow_up_reminder'
      }
    });
  
    return {
      escalationOccurred: false,
      escalationReason: '',
      followUpNotification,
      promotionMailSent: true,
      promotionChatSent: true
    };
  }
  return { runTx3Imp1Agent };
})();
export const runTx3Imp1Agent = __aivicBundle_1_runTx3Imp1Agent.runTx3Imp1Agent;
/* AIVIC_FUNCTION_BUNDLE_END owner=runTx3Imp1Agent */
