// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: tx-3-imp-1
// 関数: runTx3Imp1Agent

export interface FollowUpNotification {
    issuedToManager: boolean;
    escalationFlag: boolean;
    requiresHumanConfirmation: boolean;
    reason: string;
}
export interface MockDbTransaction {
    isOpen: boolean;
    isAborted: boolean;
    records: Array<{
        id: string;
        type: string;
        data: unknown;
    }>;
}
export interface Tx3Imp1AgentResult {
    escalationOccurred: boolean;
    escalationReason: string;
    followUpNotification: FollowUpNotification;
    promotionMailSent: boolean;
    promotionChatSent: boolean;
}
export interface Tx3Imp1AiClient {
    evaluateFollowUpTarget(unreportedEmployees: Array<{
        name: string;
    }>, delayedEmployees: Array<{
        name: string;
    }>): Promise<{
        isSpecialCase: boolean;
        requiresHumanReview: boolean;
        reason: string;
    }>;
}
export interface Tx3Imp1AgentInput {
    unreportedEmployees: Array<{
        name: string;
    }>;
    delayedEmployees: Array<{
        name: string;
    }>;
    aiClient: Tx3Imp1AiClient;
    dbTransaction: MockDbTransaction;
    managerNotificationHandler: (notification: FollowUpNotification) => FollowUpNotification;
}


/* AIVIC_FUNCTION_BUNDLE_START owner=runTx3Imp1Agent exports=runTx3Imp1Agent */
const __aivicBundle_1_runTx3Imp1Agent = (() => {
  async function runTx3Imp1Agent(
    input: Tx3Imp1AgentInput,
    context: Record<string, unknown>
  ): Promise<Tx3Imp1AgentResult> {
    if (context === undefined || context === null) { throw new Error("context is required"); }
    const {
      unreportedEmployees,
      delayedEmployees,
      aiClient,
      dbTransaction,
      managerNotificationHandler
    } = input;
  
    // Check if there are any employees to process
    const hasUnreportedOrDelayed =
      unreportedEmployees.length > 0 || delayedEmployees.length > 0;
  
    if (!hasUnreportedOrDelayed) {
      // No catalysts for follow-up
      return {
        escalationOccurred: false,
        escalationReason: '',
        followUpNotification: {
          issuedToManager: false,
          escalationFlag: false,
          requiresHumanConfirmation: false,
          reason: ''
        },
        promotionMailSent: false,
        promotionChatSent: false
      };
    }
  
    // Evaluate if this is a special case that requires human review
    const aiEvaluation = await aiClient.evaluateFollowUpTarget(
      unreportedEmployees,
      delayedEmployees
    );
  
    if (aiEvaluation.isSpecialCase || aiEvaluation.requiresHumanReview) {
      // Special case detected: escalate without side effects
      dbTransaction.isAborted = true;
  
      const escalationReason = 'special_case_not_matching_rules';
      const followUpNotification: FollowUpNotification = {
        issuedToManager: true,
        escalationFlag: true,
        requiresHumanConfirmation: true,
        reason: escalationReason
      };
  
      // Record follow-up decision in transaction before aborting
      dbTransaction.records.push({
        id: `follow_up_decision_${Date.now()}`,
        type: 'follow_up_decision',
        data: {
          status: 'requires_human_confirmation',
          reason: escalationReason,
          unreportedEmployeeCount: unreportedEmployees.length,
          delayedEmployeeCount: delayedEmployees.length
        }
      });
  
      // Record manager escalation notification
      dbTransaction.records.push({
        id: `manager_notification_${Date.now()}`,
        type: 'manager_escalation_notification',
        data: {
          escalationTriggeredAt: new Date().toISOString(),
          requiresManagerReview: true,
          unreportedEmployees: unreportedEmployees.map((e) => e.name),
          delayedEmployees: delayedEmployees.map((e) => e.name),
          reason: escalationReason
        }
      });
  
      // Invoke manager notification handler
      managerNotificationHandler(followUpNotification);
  
      return {
        escalationOccurred: true,
        escalationReason: escalationReason,
        followUpNotification: followUpNotification,
        promotionMailSent: false,
        promotionChatSent: false
      };
    }
  
    // Standard case: apply promotion rules (not special case)
    // For now, return success with no side effects (no mail/chat sent in this scenario)
    return {
      escalationOccurred: false,
      escalationReason: '',
      followUpNotification: {
        issuedToManager: false,
        escalationFlag: false,
        requiresHumanConfirmation: false,
        reason: ''
      },
      promotionMailSent: false,
      promotionChatSent: false
    };
  }
  return { runTx3Imp1Agent };
})();
export const runTx3Imp1Agent = __aivicBundle_1_runTx3Imp1Agent.runTx3Imp1Agent;
/* AIVIC_FUNCTION_BUNDLE_END owner=runTx3Imp1Agent */
