// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02Context {
  engineerInput: {
    yesterdayAccomplishments: string;
    todayPlans: string;
    currentIssues: string;
    engineerId: string;
    engineerName: string;
    submittedAt: string;
  };
  validationRules: {
    minAccomplishmentsLength: number;
    minPlansLength: number;
    minIssuesLength: number;
    allowedIssueCategories: string[];
  };
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

export interface ValidationError {
  field: string;
  message: string;
  severity: "critical" | "high";
}

export interface ValidationWarning {
  field: string;
  message: string;
}

export function buildAction02Prompt(context: Action02Context): string {
  const {
    engineerInput,
    validationRules,
  } = context;

  const prompt = `You are a validation agent for daily report submissions in a morning meeting management system.

Your task is to validate the engineer's input for completeness and appropriateness.

Engineer Information:
- ID: ${engineerInput.engineerId}
- Name: ${engineerInput.engineerName}
- Submission Time: ${engineerInput.submittedAt}

Input Content:
- Yesterday's Accomplishments: ${engineerInput.yesterdayAccomplishments}
- Today's Plans: ${engineerInput.todayPlans}
- Current Issues: ${engineerInput.currentIssues}

Validation Rules:
- Minimum accomplishments length: ${validationRules.minAccomplishmentsLength} characters
- Minimum plans length: ${validationRules.minPlansLength} characters
- Minimum issues length: ${validationRules.minIssuesLength} characters
- Allowed issue categories: ${validationRules.allowedIssueCategories.join(", ")}

Please validate the input and respond with:
1. Whether the input is valid (true/false)
2. Any critical or high-severity errors found
3. Any warnings about the content quality
4. Specific recommendations for improvement if needed

Respond in JSON format with the following structure:
{
  "isValid": boolean,
  "errors": [
    {
      "field": string,
      "message": string,
      "severity": "critical" | "high"
    }
  ],
  "warnings": [
    {
      "field": string,
      "message": string
    }
  ],
  "recommendations": string[]
}`;

  return prompt;
}
