// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-05.ts

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  previousReportContent: {
    yesterday: string;
    today: string;
    issues: string;
  };
  submissionDeadline: string;
  systemTimestamp: string;
}

export interface Action05ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  normalizedContent: {
    yesterday: string;
    today: string;
    issues: string;
  };
}

export interface Action05PromptInput {
  context: Action05Context;
  validationRules: {
    minYesterdayLength: number;
    minTodayLength: number;
    minIssuesLength: number;
    maxYesterdayLength: number;
    maxTodayLength: number;
    maxIssuesLength: number;
  };
}

export interface Action05PromptOutput {
  version: string;
  systemPrompt: string;
  userPrompt: string;
  expectedOutputFormat: {
    type: "json";
    schema: {
      isValid: "boolean";
      errors: "string[]";
      warnings: "string[]";
      normalizedContent: {
        yesterday: "string";
        today: "string";
        issues: "string";
      };
      validationDetails: {
        yesterdayValidation: "object";
        todayValidation: "object";
        issuesValidation: "object";
      };
    };
  };
}

export function buildAction05Prompt(input: Action05PromptInput): Action05PromptOutput {
  const {
    context,
    validationRules,
  } = input;

  const systemPrompt = `You are a validation agent for daily report (日報) content submission.
Your role is to validate engineer daily reports against predefined rules and provide structured feedback.

Validation Responsibilities:
1. Check content length constraints
2. Identify missing or incomplete information
3. Detect inappropriate or suspicious content
4. Normalize and clean the input content
5. Provide clear error messages and warnings

Output Format:
Return a JSON object with validation results, normalized content, and detailed validation information.`;

  const userPrompt = `Validate the following daily report submission:

Engineer ID: ${context.engineerId}
Engineer Name: ${context.engineerName}
Report Date: ${context.reportDate}
Submission Deadline: ${context.submissionDeadline}
System Timestamp: ${context.systemTimestamp}

Content to Validate:
- Yesterday's Achievements: "${context.previousReportContent.yesterday}"
- Today's Plans: "${context.previousReportContent.today}"
- Issues/Concerns: "${context.previousReportContent.issues}"

Validation Rules:
- Yesterday's achievements: minimum ${validationRules.minYesterdayLength} characters, maximum ${validationRules.maxYesterdayLength} characters
- Today's plans: minimum ${validationRules.minTodayLength} characters, maximum ${validationRules.maxTodayLength} characters
- Issues/concerns: minimum ${validationRules.minIssuesLength} characters, maximum ${validationRules.maxIssuesLength} characters

Please validate this content and return:
1. Overall validity status
2. List of errors (if any)
3. List of warnings (if any)
4. Normalized content (cleaned and formatted)
5. Detailed validation information for each field`;

  return {
    version: ACTION_05_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    expectedOutputFormat: {
      type: "json",
      schema: {
        isValid: "boolean",
        errors: "string[]",
        warnings: "string[]",
        normalizedContent: {
          yesterday: "string",
          today: "string",
          issues: "string",
        },
        validationDetails: {
          yesterdayValidation: "object",
          todayValidation: "object",
          issuesValidation: "object",
        },
      },
    },
  };
}
