// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01Context {
  engineerId: string;
  engineerName: string;
  previousDayReportDate: string;
  reportDeadline: string;
  systemName: string;
}

export interface Action01PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action01Context;
}

export function buildAction01Prompt(context: Action01Context): Action01PromptResult {
  const systemPrompt = `You are an AI agent responsible for the first action in the daily report management system.
Your role is to generate and distribute the daily report template for the previous day's work.
You must ensure the template is clear, comprehensive, and ready for engineers to fill in.
The template should include sections for:
- Yesterday's achievements
- Today's planned tasks
- Current challenges and blockers
- Any additional notes

Be professional and encouraging in your communication.`;

  const userPrompt = `Generate a daily report template for engineer: ${context.engineerName} (ID: ${context.engineerId})
Report date: ${context.previousDayReportDate}
Submission deadline: ${context.reportDeadline}
System: ${context.systemName}

Please create a well-structured template that the engineer can easily fill in with their daily work information.
Include clear instructions and examples where appropriate.`;

  return {
    version: ACTION_01_PROMPT_VERSION,
    action: "action-01",
    systemPrompt,
    userPrompt,
    context,
  };
}
