// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-03.ts

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface Action03PromptInput {
  engineerName: string;
  engineerEmail: string;
  yesterdayReport: string;
  todayPlan: string;
  issues: string;
  submissionDeadline: string;
  systemName: string;
}

export interface Action03PromptOutput {
  prompt: string;
  version: string;
}

export function buildAction03Prompt(
  input: Action03PromptInput
): Action03PromptOutput {
  const {
    engineerName,
    engineerEmail,
    yesterdayReport,
    todayPlan,
    issues,
    submissionDeadline,
    systemName,
  } = input;

  const prompt = `You are an AI agent responsible for validating daily report submissions in the "${systemName}" system.

Engineer Information:
- Name: ${engineerName}
- Email: ${engineerEmail}
- Submission Deadline: ${submissionDeadline}

Submitted Report Content:
- Yesterday's Achievements: ${yesterdayReport}
- Today's Plan: ${todayPlan}
- Current Issues: ${issues}

Your Task (Action 3: Validate Input Content):
1. Verify that all required fields are completed and not empty
2. Check that the content is appropriate and meaningful (not placeholder text)
3. Validate that yesterday's achievements are specific and measurable
4. Validate that today's plan is clear and actionable
5. Validate that issues are clearly described with context
6. Identify any missing or incomplete information
7. Flag any content that appears to be low-quality or insufficient

Validation Criteria:
- Yesterday's Achievements: Must contain specific accomplishments (minimum 20 characters)
- Today's Plan: Must contain concrete tasks (minimum 20 characters)
- Issues: Must be clearly described if present (minimum 10 characters if provided)
- All fields must be in appropriate language and format

Output your validation result as JSON with the following structure:
{
  "isValid": boolean,
  "validationErrors": string[],
  "validationWarnings": string[],
  "summary": string,
  "recommendedAction": "approve" | "request_revision" | "escalate"
}`;

  return {
    prompt,
    version: ACTION_03_PROMPT_VERSION,
  };
}
