// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-03.ts

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface Action03PromptInput {
  engineerName: string;
  engineerEmail: string;
  yesterdayReport: string;
  todayPlan: string;
  issues: string;
  submissionDeadline: string;
  systemName: string;
}

export interface Action03PromptOutput {
  prompt: string;
  version: string;
}

export function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const prompt = `
You are an AI agent responsible for validating daily report submissions in the "朝会報告管理システム" (Morning Meeting Report Management System).

**Task: Validate Daily Report Input Content**

Engineer Information:
- Name: ${input.engineerName}
- Email: ${input.engineerEmail}
- Submission Deadline: ${input.submissionDeadline}

Submitted Report Content:
- Yesterday's Achievements: ${input.yesterdayReport}
- Today's Plan: ${input.todayPlan}
- Current Issues: ${input.issues}

**Validation Requirements:**

1. **Completeness Check**
   - Verify that all three sections (yesterday's achievements, today's plan, issues) are provided
   - Ensure each section contains meaningful content (not empty or placeholder text)
   - Check that the content length is reasonable (not too brief, not excessively long)

2. **Appropriateness Check**
   - Verify that yesterday's achievements are work-related and specific
   - Verify that today's plan is realistic and actionable
   - Verify that issues are clearly articulated and relevant to work

3. **Format Validation**
   - Check for basic grammar and clarity
   - Ensure the report follows professional communication standards
   - Verify no sensitive information is exposed

4. **Consistency Check**
   - Verify that today's plan logically follows from yesterday's achievements
   - Check for any contradictions between sections

**Output Format:**
Return a JSON object with the following structure:
{
  "isValid": boolean,
  "validationStatus": "VALID" | "INCOMPLETE" | "INAPPROPRIATE" | "ERROR",
  "issues": string[],
  "recommendations": string[],
  "canProceedToRegistration": boolean,
  "escalationRequired": boolean,
  "escalationReason": string | null
}

**Escalation Conditions:**
- If content is incomplete or missing required sections
- If content appears inappropriate or off-topic
- If the submission is significantly past the deadline
- If any content raises concerns about work quality or team dynamics

Perform the validation and return the JSON response.
  `.trim();

  return {
    prompt,
    version: ACTION_03_PROMPT_VERSION,
  };
}
