// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  previousReportContent: {
    yesterday: string;
    today: string;
    issues: string;
  };
  submissionDeadline: string;
  systemTimestamp: string;
}

export interface Action04ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  validatedContent: {
    yesterday: string;
    today: string;
    issues: string;
  };
}

export function buildAction04Prompt(context: Action04Context): string {
  const {
    engineerId,
    engineerName,
    reportDate,
    previousReportContent,
    submissionDeadline,
    systemTimestamp,
  } = context;

  const promptContent = `# 日報入力内容の妥当性検証タスク

## タスク概要
エンジニアから受け取った日報入力内容の妥当性を検証し、管理システムへの登録可否を判定してください。

## 対象エンジニア情報
- エンジニアID: ${engineerId}
- エンジニア名: ${engineerName}
- 報告日: ${reportDate}
- システム時刻: ${systemTimestamp}
- 提出期限: ${submissionDeadline}

## 受け取った入力内容
### 昨日の実績
${previousReportContent.yesterday}

### 本日の予定
${previousReportContent.today}

### 抱えている課題
${previousReportContent.issues}

## 検証ルール
1. **必須項目の完全性**
   - 昨日の実績: 100文字以上、具体的な成果が記載されているか
   - 本日の予定: 100文字以上、実現可能な計画が記載されているか
   - 抱えている課題: 50文字以上、明確な課題が記載されているか

2. **内容の妥当性**
   - 昨日の実績が実現不可能な内容でないか
   - 本日の予定が過度に楽観的でないか
   - 課題の記述が具体的で対応可能な内容か

3. **形式の適切性**
   - テキストが適切にフォーマットされているか
   - 不適切な文字や記号が含まれていないか
   - 個人情報が含まれていないか

4. **論理的一貫性**
   - 昨日の実績と本日の予定に矛盾がないか
   - 課題が昨日の実績や本日の予定と関連性があるか

## 出力形式
JSON形式で以下の構造で返してください：
{
  "isValid": boolean,
  "errors": string[],
  "warnings": string[],
  "validatedContent": {
    "yesterday": string,
    "today": string,
    "issues": string
  }
}

## 判定基準
- isValid: true の場合、管理システムへの登録を進める
- isValid: false の場合、エンジニアに修正を依頼する
- errors: 登録を阻止する重大な問題
- warnings: 登録は可能だが注意が必要な問題
- validatedContent: 検証後の確定内容（修正・正規化済み）`;

  return promptContent;
}
