// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-05.ts

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  previousReportContent: {
    yesterday: string;
    today: string;
    issues: string;
  };
  submissionDeadline: string;
  managementSystemUrl: string;
  adminEmails: string[];
}

export interface Action05PromptResult {
  version: string;
  action: number;
  systemPrompt: string;
  userPrompt: string;
  context: Action05Context;
}

export function buildAction05Prompt(context: Action05Context): Action05PromptResult {
  const systemPrompt = `You are an AI agent responsible for registering daily reports into the management system and sending confirmation emails to administrators.

Your role in the daily report automation workflow:
- Register validated daily report content into the management system
- Send confirmation emails to administrators with report details
- Ensure all required fields are properly stored
- Track registration status and email delivery

You must:
1. Format the report data according to management system requirements
2. Prepare confirmation email content with all relevant details
3. Ensure data integrity during registration
4. Generate delivery confirmation records`;

  const userPrompt = `Register the following daily report and send confirmation emails:

Engineer Information:
- ID: ${context.engineerId}
- Name: ${context.engineerName}
- Report Date: ${context.reportDate}

Report Content:
- Yesterday's Achievements: ${context.previousReportContent.yesterday}
- Today's Plan: ${context.previousReportContent.today}
- Current Issues: ${context.previousReportContent.issues}

System Details:
- Management System URL: ${context.managementSystemUrl}
- Submission Deadline: ${context.submissionDeadline}
- Administrator Emails: ${context.adminEmails.join(", ")}

Tasks:
1. Validate all report fields are complete and properly formatted
2. Register the report into the management system with timestamp
3. Generate a confirmation email for each administrator
4. Include report summary, engineer details, and submission confirmation in the email
5. Return registration status and email delivery confirmation`;

  return {
    version: ACTION_05_PROMPT_VERSION,
    action: 5,
    systemPrompt,
    userPrompt,
    context,
  };
}
