// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-05.ts

export const ACTION_05_PROMPT_VERSION = "1.0.0";

export interface Action05Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  submittedReportContent: {
    yesterdayAccomplishments: string;
    todayPlans: string;
    currentIssues: string;
  };
  submissionTimestamp: string;
  systemRegistrationStatus: "pending" | "success" | "failed";
  registrationErrorMessage?: string;
}

export interface Action05PromptInput {
  context: Action05Context;
  adminEmailAddresses: string[];
  reportManagementSystemName: string;
  confirmationEmailTemplate?: string;
}

export interface Action05PromptOutput {
  promptText: string;
  version: string;
  actionType: "send_confirmation_email";
  targetAudience: "admin";
}

export function buildAction05Prompt(
  input: Action05PromptInput
): Action05PromptOutput {
  const {
    context,
    adminEmailAddresses,
    reportManagementSystemName,
    confirmationEmailTemplate,
  } = input;

  const basePrompt = `You are an automated email dispatch agent for the morning report management system.

## Task: Send Confirmation Email to Administrators

### Report Details
- Engineer ID: ${context.engineerId}
- Engineer Name: ${context.engineerName}
- Report Date: ${context.reportDate}
- Submission Timestamp: ${context.submissionTimestamp}
- System Registration Status: ${context.systemRegistrationStatus}

### Report Content
**Yesterday's Accomplishments:**
${context.submittedReportContent.yesterdayAccomplishments}

**Today's Plans:**
${context.submittedReportContent.todayPlans}

**Current Issues:**
${context.submittedReportContent.currentIssues}

### Recipients
${adminEmailAddresses.map((email) => `- ${email}`).join("\n")}

### System Information
- Report Management System: ${reportManagementSystemName}
- Registration Status: ${context.systemRegistrationStatus}${
    context.registrationErrorMessage
      ? `\n- Error Details: ${context.registrationErrorMessage}`
      : ""
  }

### Email Composition Instructions
1. Generate a professional confirmation email
2. Include all report details in a clear, structured format
3. Confirm successful registration in the ${reportManagementSystemName}
4. Provide timestamp of confirmation
5. Include system reference ID for tracking
6. Add footer with system information

### Email Template Override
${
  confirmationEmailTemplate
    ? `Use the following template as base:\n${confirmationEmailTemplate}`
    : "Use standard professional business email format"
}

### Output Requirements
- Email Subject: Clear, includes engineer name and date
- Email Body: Well-formatted, includes all report sections
- Recipient List: All administrator email addresses
- Send Status: Confirmation of dispatch`;

  return {
    promptText: basePrompt,
    version: ACTION_05_PROMPT_VERSION,
    actionType: "send_confirmation_email",
    targetAudience: "admin",
  };
}
