// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-03.ts

export const ACTION_03_PROMPT_VERSION = "1.0.0";

export interface Action03Input {
  engineerName: string;
  engineerEmail: string;
  yesterdayAccomplishments: string;
  todayPlans: string;
  currentIssues: string;
  submissionTimestamp: string;
}

export interface Action03ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

export interface Action03RegistrationPayload {
  engineerName: string;
  engineerEmail: string;
  yesterdayAccomplishments: string;
  todayPlans: string;
  currentIssues: string;
  submissionTimestamp: string;
  validationStatus: "valid" | "warning";
}

export function buildAction03Prompt(input: Action03Input): string {
  const prompt = `You are validating a daily report submission from an engineer.

Engineer Information:
- Name: ${input.engineerName}
- Email: ${input.engineerEmail}
- Submission Time: ${input.submissionTimestamp}

Report Content:
- Yesterday's Accomplishments: ${input.yesterdayAccomplishments}
- Today's Plans: ${input.todayPlans}
- Current Issues: ${input.currentIssues}

Task: Validate the input content for completeness and appropriateness.

Validation Criteria:
1. All fields must be filled (not empty or null)
2. Yesterday's accomplishments should describe concrete work completed
3. Today's plans should be specific and actionable
4. Current issues should be clearly articulated if any exist
5. Content should be professional and relevant to work

Respond with a JSON object containing:
{
  "isValid": boolean,
  "errors": string[],
  "warnings": string[],
  "summary": string
}

Errors are blocking issues that prevent registration.
Warnings are non-blocking concerns that should be noted.`;

  return prompt;
}
