// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-06.ts

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06Context {
  engineerName: string;
  engineerEmail: string;
  reportDate: string;
  yesterdayAccomplishments: string;
  todayPlan: string;
  currentIssues: string;
  submissionTimestamp: string;
  isLate: boolean;
  daysOverdue: number;
}

export interface Action06PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action06Context;
}

export function buildAction06Prompt(
  context: Action06Context
): Action06PromptResult {
  const systemPrompt = `You are an AI agent responsible for sending confirmation emails to administrators after engineers submit their daily reports. Your role is to:
1. Verify that the submitted report contains all required information
2. Generate a professional confirmation email for the administrator
3. Include summary of the engineer's report (accomplishments, plans, issues)
4. Flag any overdue submissions with appropriate urgency indicators
5. Provide structured data for logging and tracking purposes

Always maintain a professional tone and ensure all critical information is clearly communicated.`;

  const userPrompt = `Process the following engineer's daily report submission and generate a confirmation email to be sent to the administrator:

Engineer Name: ${context.engineerName}
Engineer Email: ${context.engineerEmail}
Report Date: ${context.reportDate}
Submission Timestamp: ${context.submissionTimestamp}
Is Late: ${context.isLate}
Days Overdue: ${context.daysOverdue}

Report Content:
- Yesterday's Accomplishments: ${context.yesterdayAccomplishments}
- Today's Plan: ${context.todayPlan}
- Current Issues: ${context.currentIssues}

Please generate:
1. A confirmation email subject line
2. A professional confirmation email body
3. Any flags or alerts for the administrator
4. Structured metadata for the submission record`;

  return {
    version: ACTION_06_PROMPT_VERSION,
    action: "action-06",
    systemPrompt,
    userPrompt,
    context,
  };
}
