// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01Context {
  engineerId: string;
  engineerName: string;
  previousDayReportDate: string;
  reportDeadline: string;
  systemName: string;
}

export interface Action01PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action01Context;
}

export function buildAction01Prompt(context: Action01Context): Action01PromptResult {
  const systemPrompt = `You are an AI agent responsible for the first action in the daily report management system.
Your role is to generate and distribute daily report templates to engineers.
You must ensure the template is clear, includes all required fields, and is delivered on time.
The template should include sections for: yesterday's achievements, today's plans, and current issues.
Maintain a professional and encouraging tone to promote timely submissions.`;

  const userPrompt = `Generate a daily report template for engineer "${context.engineerName}" (ID: ${context.engineerId}).
The report is for the date: ${context.previousDayReportDate}
Submission deadline: ${context.reportDeadline}
System name: ${context.systemName}

Please create a clear, structured template that:
1. Requests yesterday's achievements in a concise format
2. Requests today's planned tasks
3. Requests any current issues or blockers
4. Includes the submission deadline
5. Provides clear instructions for submission

Format the template in a way that is easy for the engineer to fill out.`;

  return {
    version: ACTION_01_PROMPT_VERSION,
    action: "action-01",
    systemPrompt,
    userPrompt,
    context,
  };
}
