// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  submittedContent: {
    yesterdayAccomplishment: string;
    todayPlan: string;
    issues: string;
  };
  submissionTimestamp: string;
}

export interface Action04ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

export interface Action04RegistrationResult {
  success: boolean;
  reportId: string;
  registeredAt: string;
  message: string;
}

export interface Action04PromptInput {
  context: Action04Context;
  validationRules: {
    minYesterdayLength: number;
    minTodayLength: number;
    minIssuesLength: number;
    maxYesterdayLength: number;
    maxTodayLength: number;
    maxIssuesLength: number;
  };
}

export interface Action04PromptOutput {
  action: "register" | "reject" | "escalate";
  validation: Action04ValidationResult;
  registration?: Action04RegistrationResult;
  escalationReason?: string;
  nextAction: string;
}

export function buildAction04Prompt(input: Action04PromptInput): string {
  const {
    context,
    validationRules,
  } = input;

  const prompt = `You are an AI agent responsible for validating and registering daily reports in the morning meeting management system.

## Current Task: Validate and Register Daily Report (Action 04)

### Engineer Information
- Engineer ID: ${context.engineerId}
- Engineer Name: ${context.engineerName}
- Report Date: ${context.reportDate}
- Submission Timestamp: ${context.submissionTimestamp}

### Submitted Content
**Yesterday's Accomplishment:**
${context.submittedContent.yesterdayAccomplishment}

**Today's Plan:**
${context.submittedContent.todayPlan}

**Issues/Challenges:**
${context.submittedContent.issues}

### Validation Rules
- Minimum yesterday accomplishment length: ${validationRules.minYesterdayLength} characters
- Minimum today plan length: ${validationRules.minTodayLength} characters
- Minimum issues length: ${validationRules.minIssuesLength} characters
- Maximum yesterday accomplishment length: ${validationRules.maxYesterdayLength} characters
- Maximum today plan length: ${validationRules.maxTodayLength} characters
- Maximum issues length: ${validationRules.maxIssuesLength} characters

### Your Task
1. Validate the submitted content against the validation rules
2. Check for completeness and appropriateness of the report
3. Identify any errors or warnings
4. Determine if the report should be registered, rejected, or escalated
5. If valid, prepare for registration in the management system

### Validation Criteria
- All fields must meet minimum length requirements
- All fields must not exceed maximum length requirements
- Content must be coherent and relevant to the report date
- No placeholder or empty-like content
- Language and format must be appropriate for a professional report

### Output Format
Respond with a JSON object containing:
{
  "action": "register" | "reject" | "escalate",
  "validation": {
    "isValid": boolean,
    "errors": string[],
    "warnings": string[]
  },
  "registration": {
    "success": boolean,
    "reportId": string,
    "registeredAt": string,
    "message": string
  },
  "escalationReason": string (if action is "escalate"),
  "nextAction": string
}

### Decision Logic
- If all validations pass: action = "register"
- If critical validations fail: action = "reject"
- If content is suspicious or requires human review: action = "escalate"
- If system error occurs: action = "escalate"

Proceed with validation and provide your response in the specified JSON format.`;

  return prompt;
}
