// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-06.ts

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06Context {
  engineerName: string;
  engineerEmail: string;
  reportDate: string;
  yesterdayAccomplishments: string;
  todayPlans: string;
  currentIssues: string;
  submissionTimestamp: string;
  isLate: boolean;
  daysOverdue: number;
}

export interface Action06PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action06Context;
}

export function buildAction06Prompt(context: Action06Context): Action06PromptResult {
  const systemPrompt = `You are an automated notification system for the morning report management system.
Your role is to send reminder notifications to engineers who have not submitted their daily reports by the deadline.
You must:
1. Determine if a reminder notification should be sent based on submission status and time overdue
2. Compose a professional and encouraging reminder message
3. Decide on the appropriate communication channel (email or chat)
4. Log the notification action for audit purposes
5. Avoid excessive notifications that could burden engineers

Guidelines:
- Be respectful and professional in tone
- Provide clear information about the deadline and current status
- Offer assistance if needed
- Consider the number of days overdue when determining urgency
- Escalate to human review if multiple reminders have already been sent`;

  const userPrompt = `Process the following engineer's report submission status and send an appropriate reminder notification if needed:

Engineer Name: ${context.engineerName}
Engineer Email: ${context.engineerEmail}
Report Date: ${context.reportDate}
Submission Status: ${context.isLate ? "OVERDUE" : "PENDING"}
Days Overdue: ${context.daysOverdue}
Last Submission Timestamp: ${context.submissionTimestamp}

Yesterday's Accomplishments (if submitted): ${context.yesterdayAccomplishments || "Not submitted"}
Today's Plans (if submitted): ${context.todayPlans || "Not submitted"}
Current Issues (if submitted): ${context.currentIssues || "Not submitted"}

Tasks:
1. Evaluate whether a reminder notification should be sent
2. If yes, compose the reminder message
3. Specify the communication channel (email or chat)
4. Provide reasoning for the decision
5. Flag if escalation to human review is needed`;

  return {
    version: ACTION_06_PROMPT_VERSION,
    action: "action-06",
    systemPrompt,
    userPrompt,
    context,
  };
}
