// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-06.ts

export const ACTION_06_PROMPT_VERSION = "1.0.0";

export interface Action06Context {
  engineerName: string;
  engineerEmail: string;
  reportDate: string;
  submissionDeadline: string;
  previousReportTemplate?: string;
  systemApiEndpoint: string;
  adminEmails: string[];
}

export interface Action06PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action06Context;
}

export function buildAction06Prompt(context: Action06Context): Action06PromptResult {
  const systemPrompt = `You are an automated daily report management agent responsible for sending confirmation emails to administrators after a daily report has been successfully registered in the system.

Your role in Action 6 is to:
1. Verify that the daily report was successfully registered in the management system
2. Compose and send confirmation emails to all specified administrators
3. Include relevant report details and submission confirmation in the email
4. Log the email sending results for audit purposes
5. Handle any email delivery failures gracefully

You must ensure:
- Confirmation emails are sent to all administrators in the admin email list
- Email content clearly indicates successful report registration
- The engineer's name, report date, and key submission details are included
- Email sending is logged with timestamp and delivery status
- Any failures are reported for escalation`;

  const userPrompt = `Please send confirmation emails for the following daily report submission:

Engineer Name: ${context.engineerName}
Engineer Email: ${context.engineerEmail}
Report Date: ${context.reportDate}
Submission Deadline: ${context.submissionDeadline}
System API Endpoint: ${context.systemApiEndpoint}
Administrator Email List: ${context.adminEmails.join(", ")}

${context.previousReportTemplate ? `Previous Report Template Reference:\n${context.previousReportTemplate}\n` : ""}

Action 6 Task: Send Confirmation Emails to Administrators

Steps to execute:
1. Verify the report registration status in the management system
2. Prepare a professional confirmation email with:
   - Subject: Daily Report Submission Confirmation - [Engineer Name] - [Report Date]
   - Body including: engineer name, submission timestamp, report date, confirmation of successful registration
3. Send the confirmation email to each administrator
4. Record the sending timestamp and delivery status for each email
5. If any email fails to send, log the failure reason and prepare for escalation

Expected output:
- Confirmation that emails were sent to all administrators
- List of email addresses that received the confirmation
- Timestamp of email sending
- Any delivery failures or issues encountered`;

  return {
    version: ACTION_06_PROMPT_VERSION,
    action: "action-06",
    systemPrompt,
    userPrompt,
    context,
  };
}
