// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02Context {
  engineerInputs: {
    yesterdayResults: string;
    todayPlans: string;
    currentIssues: string;
    engineerId: string;
    engineerName: string;
    submissionTime: string;
  };
}

export interface Action02ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  validatedData: {
    yesterdayResults: string;
    todayPlans: string;
    currentIssues: string;
    engineerId: string;
    engineerName: string;
    submissionTime: string;
  };
}

export function buildAction02Prompt(context: Action02Context): string {
  const {
    engineerInputs: {
      yesterdayResults,
      todayPlans,
      currentIssues,
      engineerId,
      engineerName,
      submissionTime,
    },
  } = context;

  return `You are a validation agent for daily report submissions in the morning meeting management system.

Your task is to validate the engineer's input content for completeness and appropriateness.

Engineer Information:
- ID: ${engineerId}
- Name: ${engineerName}
- Submission Time: ${submissionTime}

Input Content to Validate:
1. Yesterday's Results:
${yesterdayResults}

2. Today's Plans:
${todayPlans}

3. Current Issues:
${currentIssues}

Validation Criteria:
1. Completeness: All three sections must have meaningful content (not empty or just whitespace)
2. Length: Each section should have at least 10 characters of substantive content
3. Appropriateness: Content should be work-related and coherent
4. Format: No excessive special characters or malformed text
5. Relevance: Content should be relevant to daily report context

Please validate the input and respond with:
- A boolean indicating if the input is valid
- A list of any errors found (validation failures)
- A list of any warnings (minor issues that don't prevent submission)
- The validated/cleaned data if valid

Respond in JSON format with the following structure:
{
  "isValid": boolean,
  "errors": string[],
  "warnings": string[],
  "validatedData": {
    "yesterdayResults": string,
    "todayPlans": string,
    "currentIssues": string,
    "engineerId": string,
    "engineerName": string,
    "submissionTime": string
  }
}`;
}
