// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02Input {
  engineerName: string;
  engineerEmail: string;
  yesterdayAccomplishments: string;
  todayPlans: string;
  currentIssues: string;
  submissionTimestamp: string;
}

export interface Action02ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

export interface Action02Output {
  validationResult: Action02ValidationResult;
  reportId?: string;
  registrationStatus: "pending" | "success" | "failed";
  message: string;
}

export function buildAction02Prompt(input: Action02Input): string {
  const prompt = `You are validating a daily report submission for an engineer.

Engineer Information:
- Name: ${input.engineerName}
- Email: ${input.engineerEmail}
- Submission Time: ${input.submissionTimestamp}

Report Content:
- Yesterday's Accomplishments: ${input.yesterdayAccomplishments}
- Today's Plans: ${input.todayPlans}
- Current Issues: ${input.currentIssues}

Please validate the following:
1. All required fields are filled (not empty)
2. Content is appropriate and professional
3. Yesterday's accomplishments are specific and measurable
4. Today's plans are clear and achievable
5. Current issues are clearly described

Respond with a JSON object containing:
{
  "isValid": boolean,
  "errors": string[],
  "warnings": string[]
}

Errors should be critical issues that prevent registration.
Warnings should be minor issues that don't prevent registration but should be noted.`;

  return prompt;
}
