// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-1-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Action01Context {
  engineerId: string;
  engineerName: string;
  previousDayReportDate: string;
  reportDeadline: string;
  systemUrl: string;
}

export interface Action01PromptResult {
  version: string;
  action: string;
  systemPrompt: string;
  userPrompt: string;
  context: Action01Context;
}

export function buildAction01Prompt(context: Action01Context): Action01PromptResult {
  const systemPrompt = `You are an AI agent responsible for generating and distributing daily report templates for engineers.
Your role is to:
1. Generate a daily report template based on the previous day's report
2. Prepare the template for distribution to the engineer
3. Ensure the template includes sections for: yesterday's achievements, today's plans, and current issues
4. Format the template in a clear, structured manner that encourages complete and timely submission

You must maintain consistency with the previous day's report structure while allowing for new entries.
Always include the submission deadline and system URL for reference.`;

  const userPrompt = `Generate a daily report template for engineer: ${context.engineerName} (ID: ${context.engineerId})
Previous report date: ${context.previousDayReportDate}
Submission deadline: ${context.reportDeadline}
System URL: ${context.systemUrl}

Please create a template that:
- References yesterday's report date
- Includes clear sections for yesterday's achievements, today's plans, and current issues
- Specifies the submission deadline
- Provides the system URL for submission
- Is formatted for easy reading and completion`;

  return {
    version: ACTION_01_PROMPT_VERSION,
    action: "action-01",
    systemPrompt,
    userPrompt,
    context,
  };
}
