// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/db.ts

// src/db.ts

// In-memory storage for all entities
const transactionLogs: Array<{
  exec_id: string;
  action_type: string;
  count: number;
}> = [];

const mailSendLogs: Array<{
  exec_id: string;
  recipient_id: string;
  mail_type: string;
}> = [];

const extractedIssues: Array<{
  exec_id: string;
  issue_id: string;
}> = [];

const priorityJudgmentLogs: Array<{
  exec_id: string;
  judgment_result: string;
}> = [];

const confirmationEmailHistories: Array<{
  exec_id?: string;
  [key: string]: unknown;
}> = [];

export async function insertConfirmationEmailHistory(
  data: Record<string, unknown>
): Promise<void> {
  confirmationEmailHistories.push(data);
}

export async function getTransactionLogByExecId(
  exec_id: string
): Promise<
  Array<{
    exec_id: string;
    action_type: string;
    count: number;
  }>
> {
  return transactionLogs.filter((log) => log.exec_id === exec_id);
}

export async function insertTransactionLog(data: {
  exec_id: string;
  action_type: string;
  count: number;
}): Promise<{ inserted: boolean }> {
  transactionLogs.push(data);
  return { inserted: true };
}

export async function getMailSendLogsByExecId(
  exec_id: string
): Promise<
  Array<{
    exec_id: string;
    recipient_id: string;
    mail_type: string;
  }>
> {
  return mailSendLogs.filter((log) => log.exec_id === exec_id);
}

export async function insertMailSendLog(data: {
  exec_id: string;
  recipient_id: string;
  mail_type: string;
}): Promise<{ inserted: boolean }> {
  mailSendLogs.push(data);
  return { inserted: true };
}

export async function getExtractedIssuesByExecId(
  exec_id: string
): Promise<
  Array<{
    exec_id: string;
    issue_id: string;
  }>
> {
  return extractedIssues.filter((issue) => issue.exec_id === exec_id);
}

export async function insertExtractedIssue(data: {
  exec_id: string;
  issue_id: string;
}): Promise<{ inserted: boolean }> {
  extractedIssues.push(data);
  return { inserted: true };
}

export async function getPriorityJudgmentLogsByExecId(
  exec_id: string
): Promise<
  Array<{
    exec_id: string;
    judgment_result: string;
  }>
> {
  return priorityJudgmentLogs.filter((log) => log.exec_id === exec_id);
}

export async function insertPriorityJudgmentLog(data: {
  exec_id: string;
  judgment_result: string;
}): Promise<{ inserted: boolean }> {
  priorityJudgmentLogs.push(data);
  return { inserted: true };
}
