// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/types.ts

export interface User {
  id: string;
  name: string;
  email: string;
  departmentId: string;
  role: "manager" | "engineer" | "admin";
  status: "active" | "inactive";
  createdAt: Date;
  updatedAt: Date;
}

export interface Department {
  id: string;
  name: string;
  parentDepartmentId: string | null;
  status: "active" | "inactive";
  createdAt: Date;
  updatedAt: Date;
}

export interface DailyReport {
  id: string;
  userId: string;
  reportDate: Date;
  yesterday: string;
  today: string;
  issues: string;
  status: "submitted" | "draft" | "pending";
  createdAt: Date;
  updatedAt: Date;
}

export interface ReportSubmissionHistory {
  id: string;
  userId: string;
  reportId: string;
  submittedAt: Date;
  submitterUserId: string;
  status: "completed" | "pending" | "failed";
  createdAt: Date;
}

export interface AuditLog {
  id?: string;
  agentId: string;
  eventType:
    | "started"
    | "completed"
    | "failed"
    | "step_in_progress"
    | "step_completed"
    | "handoff";
  stepName?: string;
  timestamp: Date;
  details: Record<string, unknown>;
  createdAt?: Date;
}
