// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/orchestrator.ts
export { runTx2Imp1Agent } from "../../logic/it-1";
export type { Tx2Imp1AiClient } from "../../logic/it-1";
