// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/types.ts
export type { Tx2Imp1AiClient, Tx2Imp1AgentInput, Tx2Imp1AgentOutput, EscalationNotification } from "../../logic/it-1";
