// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportingDeadline: string;
  overdueThresholdMinutes: number;
  notificationChannels: string[];
  escalationRules: {
    repeatOffenderThreshold: number;
    systemErrorHandling: string;
  };
}

export interface Action02PromptOutput {
  prompt: string;
  version: string;
  metadata: {
    action: string;
    contract: string;
    purpose: string;
  };
}

export function buildAction02Prompt(input: Action02PromptInput): Action02PromptOutput {
  const {
    reportingDeadline,
    overdueThresholdMinutes,
    notificationChannels,
    escalationRules,
  } = input;

  const channelsList = notificationChannels.join(", ");

  const prompt = `You are an AI agent responsible for Action 2 of the Daily Report Management System (tx_2_imp_1).

## Your Task
Identify unreported and delayed team members from the daily report submission status, and notify the department head.

## Context
- Reporting Deadline: ${reportingDeadline}
- Overdue Threshold: ${overdueThresholdMinutes} minutes
- Notification Channels: ${channelsList}
- Repeat Offender Threshold: ${escalationRules.repeatOffenderThreshold} occurrences
- System Error Handling: ${escalationRules.systemErrorHandling}

## Autonomous Actions to Execute
1. Check the submission status of all team members at the configured time
2. Automatically identify unreported and delayed members
3. Create a list of unreported and delayed members
4. Send notification email to the department head

## Escalation Conditions
- System failure preventing report submission status verification
- Repeated reporting failures by specific team members requiring intervention decision

## Output Requirements
- Provide a structured list of unreported members with timestamps
- Provide a structured list of delayed members with submission times
- Include recommendation for escalation if applicable
- Log all actions taken with timestamps

## Constraints
- Do not make assumptions about member availability
- Verify data integrity before reporting
- Maintain audit trail of all notifications sent`;

  return {
    prompt,
    version: ACTION_02_PROMPT_VERSION,
    metadata: {
      action: "action-02",
      contract: "tx_2_imp_1",
      purpose: "Identify unreported and delayed team members and notify department head",
    },
  };
}
