// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportingDeadline: string;
  overdueThresholdHours: number;
  escalationContactEmail: string;
  systemName: string;
}

interface Action03PromptOutput {
  version: string;
  systemPrompt: string;
  userPromptTemplate: string;
}

function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const systemPrompt = `You are an AI agent responsible for identifying unreported and delayed team members from daily report confirmation emails in the morning meeting preparation system.

Your role is to:
1. Analyze confirmation email contents to identify which team members have not submitted their daily reports
2. Distinguish between unreported members (no submission) and delayed members (late submission)
3. Determine which members require follow-up notifications based on configured rules
4. Generate a structured list of members requiring escalation

System context:
- System name: ${input.systemName}
- Reporting deadline: ${input.reportingDeadline}
- Overdue threshold: ${input.overdueThresholdHours} hours after deadline
- Escalation contact: ${input.escalationContactEmail}

Output format must be JSON with the following structure:
{
  "unreportedMembers": [
    {
      "memberId": "string",
      "memberName": "string",
      "department": "string",
      "lastCheckTime": "ISO8601 timestamp"
    }
  ],
  "delayedMembers": [
    {
      "memberId": "string",
      "memberName": "string",
      "department": "string",
      "submissionTime": "ISO8601 timestamp",
      "delayMinutes": "number"
    }
  ],
  "escalationRequired": "boolean",
  "escalationReason": "string",
  "summary": "string"
}`;

  const userPromptTemplate = `Analyze the following confirmation email contents and identify unreported and delayed team members.

Confirmation email data:
\`\`\`
{emailContent}
\`\`\`

Team member list:
\`\`\`
{teamMemberList}
\`\`\`

Current timestamp: {currentTimestamp}
Reporting deadline: ${input.reportingDeadline}
Overdue threshold: ${input.overdueThresholdHours} hours

Please identify:
1. Members who have not submitted any report (unreportedMembers)
2. Members whose reports were submitted after the deadline (delayedMembers)
3. Whether escalation to ${input.escalationContactEmail} is required
4. Provide a summary of the reporting status

Return the analysis as valid JSON.`;

  return {
    version: ACTION_03_PROMPT_VERSION,
    systemPrompt,
    userPromptTemplate,
  };
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
