// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-01.ts

export const ACTION_01_PROMPT_VERSION = "1.0.0";

export interface Tx2Imp1Context {
  engineerId: string;
  engineerName: string;
  reportDate: string;
  submissionDeadline: string;
  currentTime: string;
}

export interface Tx2Imp1ReportStatus {
  engineerId: string;
  engineerName: string;
  submitted: boolean;
  submittedAt?: string;
  isLate: boolean;
}

export interface Tx2Imp1ActionInput {
  context: Tx2Imp1Context;
  reportStatuses: Tx2Imp1ReportStatus[];
}

export interface Tx2Imp1ActionOutput {
  action: string;
  timestamp: string;
  unsubmittedEngineers: Tx2Imp1ReportStatus[];
  lateEngineers: Tx2Imp1ReportStatus[];
  summary: string;
}

export function buildAction01Prompt(input: Tx2Imp1ActionInput): string {
  const { context, reportStatuses } = input;

  const unsubmittedCount = reportStatuses.filter((s) => !s.submitted).length;
  const lateCount = reportStatuses.filter((s) => s.isLate && s.submitted).length;

  const unsubmittedList = reportStatuses
    .filter((s) => !s.submitted)
    .map((s) => `- ${s.engineerName} (ID: ${s.engineerId})`)
    .join("\n");

  const lateList = reportStatuses
    .filter((s) => s.isLate && s.submitted)
    .map((s) => `- ${s.engineerName} (ID: ${s.engineerId}): 提出時刻 ${s.submittedAt}`)
    .join("\n");

  const prompt = `# 日報収集から報告漏れ特定までの自動判定と通知 - Action 1

## 実行コンテキスト
- 報告日: ${context.reportDate}
- 提出期限: ${context.submissionDeadline}
- 現在時刻: ${context.currentTime}
- 対象エンジニア数: ${reportStatuses.length}

## 日報送信状況の確認結果

### 未提出者 (${unsubmittedCount}名)
${unsubmittedCount > 0 ? unsubmittedList : "なし"}

### 遅延者 (${lateCount}名)
${lateCount > 0 ? lateList : "なし"}

## タスク
以下の情報に基づいて、報告漏れ・遅延部員の一覧を作成してください:

1. 未提出者を特定する
2. 提出期限を超過した遅延者を特定する
3. 報告漏れ・遅延部員の一覧を構造化して出力する
4. 部長への通知内容を準備する

## 出力形式
JSON形式で以下の構造で返してください:
{
  "action": "check_report_status",
  "timestamp": "ISO8601形式の現在時刻",
  "unsubmittedEngineers": [
    {
      "engineerId": "string",
      "engineerName": "string",
      "submitted": false,
      "isLate": true
    }
  ],
  "lateEngineers": [
    {
      "engineerId": "string",
      "engineerName": "string",
      "submitted": true,
      "submittedAt": "ISO8601形式の提出時刻",
      "isLate": true
    }
  ],
  "summary": "部長への通知内容（日本語）"
}`;

  return prompt;
}
