// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-02.ts

export const ACTION_02_PROMPT_VERSION = "1.0.0";

export interface Action02PromptInput {
  reportDate: string;
  targetEngineers: Array<{
    id: string;
    name: string;
    email: string;
  }>;
  submissionDeadline: string;
  systemContext: string;
}

export interface Action02PromptOutput {
  prompt: string;
  version: string;
}

export function buildAction02Prompt(input: Action02PromptInput): Action02PromptOutput {
  const engineerList = input.targetEngineers
    .map((eng) => `- ${eng.name} (${eng.email})`)
    .join("\n");

  const prompt = `You are an AI agent responsible for monitoring daily report submission status.

Context:
- Report Date: ${input.reportDate}
- Submission Deadline: ${input.submissionDeadline}
- System Context: ${input.systemContext}

Target Engineers:
${engineerList}

Task: Automatically determine which engineers have not submitted their daily reports and which have submitted late. Create a list of non-submitters and late submitters.

Requirements:
1. Check the submission status of each engineer
2. Identify engineers who have not submitted by the deadline
3. Identify engineers who submitted after the deadline
4. Generate a comprehensive list with submission status for each engineer
5. Prepare notification content for the department head

Output Format:
- Non-submitters: [list of engineer names and emails]
- Late submitters: [list of engineer names, emails, and submission time]
- Summary: [brief summary of submission status]
- Recommended Actions: [suggested next steps]`;

  return {
    prompt,
    version: ACTION_02_PROMPT_VERSION,
  };
}
