// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportingDeadline: string;
  currentTime: string;
  nonSubmitters: Array<{
    employeeId: string;
    employeeName: string;
    department: string;
  }>;
  delayedSubmitters: Array<{
    employeeId: string;
    employeeName: string;
    department: string;
    submittedAt: string;
  }>;
  escalationThreshold: number;
}

interface Action03PromptOutput {
  version: string;
  systemPrompt: string;
  userPrompt: string;
  context: {
    taskDescription: string;
    objectives: string[];
    constraints: string[];
  };
}

function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const systemPrompt = `You are an AI agent responsible for identifying non-submitters and delayed submitters of daily reports in a morning meeting management system.

Your role is to:
1. Analyze the current reporting status against the deadline
2. Identify employees who have not submitted their reports
3. Identify employees who submitted reports after the deadline
4. Determine escalation priority based on submission delay duration
5. Prepare a structured list for manager notification

You must be precise and objective in your analysis. All timestamps should be compared against the reporting deadline: ${input.reportingDeadline}

Current system time: ${input.currentTime}`;

  const userPrompt = `Please analyze the following daily report submission status and prepare a notification for the department manager.

Reporting Deadline: ${input.reportingDeadline}
Current Time: ${input.currentTime}

Non-Submitters (${input.nonSubmitters.length} employees):
${input.nonSubmitters.map((emp) => `- ${emp.employeeName} (ID: ${emp.employeeId}, Department: ${emp.department})`).join("\n")}

Delayed Submitters (${input.delayedSubmitters.length} employees):
${input.delayedSubmitters.map((emp) => `- ${emp.employeeName} (ID: ${emp.employeeId}, Department: ${emp.department}, Submitted at: ${emp.submittedAt})`).join("\n")}

Escalation Threshold: ${input.escalationThreshold} minutes

Please provide:
1. Summary of submission status
2. List of non-submitters requiring immediate follow-up
3. List of delayed submitters with delay duration
4. Escalation priority classification
5. Recommended actions for each category`;

  return {
    version: ACTION_03_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    context: {
      taskDescription:
        "Identify and classify non-submitters and delayed submitters of daily reports for manager notification",
      objectives: [
        "Accurately identify all non-submitters against the deadline",
        "Calculate delay duration for each delayed submission",
        "Classify escalation priority based on delay threshold",
        "Prepare structured notification content for manager",
      ],
      constraints: [
        "Must use the exact reporting deadline provided",
        "Must compare all timestamps against current system time",
        "Must respect the escalation threshold for priority classification",
        "Must maintain employee privacy while providing necessary identification",
      ],
    },
  };
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
