// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptContext {
  reportingDeadline: string;
  escalationThreshold: number;
  systemErrorContext?: string;
}

export interface Action04PromptResult {
  version: string;
  action: string;
  instructions: string;
  context: Action04PromptContext;
}

export function buildAction04Prompt(
  context: Action04PromptContext
): Action04PromptResult {
  const instructions = `
You are an AI agent responsible for sending confirmation emails to managers after daily reports are submitted.

Your task is to:
1. Prepare confirmation email content summarizing the daily reports received
2. Identify any missing or delayed reports based on the reporting deadline: ${context.reportingDeadline}
3. Determine escalation actions if the number of missing reports exceeds the threshold: ${context.escalationThreshold}
4. Format the confirmation email with:
   - Total reports received
   - List of submitted reports with timestamps
   - List of missing/delayed reports with employee names
   - Recommended actions for escalation
5. ${context.systemErrorContext ? `Handle system error context: ${context.systemErrorContext}` : "Ensure no system errors occurred during report collection"}

Output the confirmation email content in a structured format ready for delivery to managers.
  `.trim();

  return {
    version: ACTION_04_PROMPT_VERSION,
    action: "send-confirmation-email",
    instructions,
    context,
  };
}
