// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-03.ts

const ACTION_03_PROMPT_VERSION = "1.0.0";

interface Action03PromptInput {
  reportingDeadline: string;
  overdueThresholdHours: number;
  escalationRules: {
    maxReminders: number;
    reminderIntervalMinutes: number;
  };
}

interface Action03PromptOutput {
  version: string;
  systemPrompt: string;
  userPromptTemplate: string;
}

function buildAction03Prompt(input: Action03PromptInput): Action03PromptOutput {
  const systemPrompt = `You are an AI agent responsible for identifying non-reporting and delayed reporting members from confirmation email content, determining escalation targets, and completing the process of sending reminder emails and chat messages.

Your role:
- Analyze confirmation email content to identify members who have not submitted reports or submitted late
- Determine which members require escalation based on defined rules
- Generate and send reminder emails and chat messages to escalation targets
- Log all sending results for audit purposes

Escalation Rules:
- Maximum reminders per member: ${input.escalationRules.maxReminders}
- Reminder interval: ${input.escalationRules.reminderIntervalMinutes} minutes
- Reporting deadline: ${input.reportingDeadline}
- Overdue threshold: ${input.overdueThresholdHours} hours

You must:
1. Parse confirmation email content accurately
2. Identify non-reporting and delayed members with clear reasoning
3. Apply escalation rules consistently
4. Generate professional reminder communications
5. Record all actions with timestamps and outcomes`;

  const userPromptTemplate = `Analyze the following confirmation email content and determine escalation targets:

Email Content:
{emailContent}

Current timestamp: {currentTimestamp}

Based on the reporting deadline of ${input.reportingDeadline} and overdue threshold of ${input.overdueThresholdHours} hours:

1. Identify members who have not submitted reports
2. Identify members whose reports are overdue
3. Determine which members meet escalation criteria (max ${input.escalationRules.maxReminders} reminders)
4. Generate reminder messages for each escalation target
5. Log the escalation decision with reasoning

Provide your analysis in the following JSON format:
{
  "nonReportingMembers": [
    {
      "memberId": string,
      "memberName": string,
      "reason": string,
      "escalationRequired": boolean
    }
  ],
  "delayedMembers": [
    {
      "memberId": string,
      "memberName": string,
      "submissionTime": string,
      "delayHours": number,
      "escalationRequired": boolean
    }
  ],
  "escalationTargets": [
    {
      "memberId": string,
      "memberName": string,
      "escalationType": "email" | "chat" | "both",
      "reminderCount": number,
      "messageContent": string
    }
  ],
  "executionLog": {
    "timestamp": string,
    "totalMembersAnalyzed": number,
    "escalationsTriggered": number,
    "notes": string
  }
}`;

  return {
    version: ACTION_03_PROMPT_VERSION,
    systemPrompt,
    userPromptTemplate,
  };
}

export { buildAction03Prompt, ACTION_03_PROMPT_VERSION };
