// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptInput {
  reportingDeadline: string;
  overdueThresholdHours: number;
  escalationRules: {
    maxReminders: number;
    reminderIntervalMinutes: number;
  };
}

export interface Action04PromptOutput {
  prompt: string;
  version: string;
  metadata: {
    action: number;
    contract: string;
    purpose: string;
  };
}

export function buildAction04Prompt(input: Action04PromptInput): Action04PromptOutput {
  const {
    reportingDeadline,
    overdueThresholdHours,
    escalationRules,
  } = input;

  const prompt = `You are an AI agent responsible for Action 4 in the Daily Report Management System (tx_2_imp_1).

Your task is to identify unreported and delayed team members based on the confirmation email content and reporting status.

Context:
- Reporting Deadline: ${reportingDeadline}
- Overdue Threshold: ${overdueThresholdHours} hours
- Maximum Reminders: ${escalationRules.maxReminders}
- Reminder Interval: ${escalationRules.reminderIntervalMinutes} minutes

Instructions:
1. Analyze the confirmation email content to identify which team members have not submitted their daily reports
2. Determine which team members have submitted reports but are past the deadline
3. Classify team members into the following categories:
   - Not Submitted: Team members with no report submission
   - Delayed: Team members who submitted but exceeded the deadline
   - On Time: Team members who submitted within the deadline
4. For each delayed or non-submitted team member, assess escalation status based on reminder history
5. Generate a structured list with the following information for each team member:
   - Name
   - Status (Not Submitted / Delayed / On Time)
   - Submission Time (if applicable)
   - Hours Overdue (if applicable)
   - Reminder Count
   - Escalation Level
6. Identify any patterns or anomalies in reporting behavior
7. Provide recommendations for escalation actions

Output Format:
Return a JSON object with:
{
  "timestamp": "ISO 8601 timestamp",
  "reportingDeadline": "${reportingDeadline}",
  "analysisResults": {
    "totalTeamMembers": number,
    "submitted": number,
    "notSubmitted": number,
    "delayed": number,
    "teamMembers": [
      {
        "name": string,
        "status": "Not Submitted" | "Delayed" | "On Time",
        "submissionTime": string | null,
        "hoursOverdue": number | null,
        "reminderCount": number,
        "escalationLevel": "Low" | "Medium" | "High" | "Critical",
        "requiresAction": boolean
      }
    ]
  },
  "escalationRecommendations": {
    "immediateAction": string[],
    "followUpRequired": string[],
    "notes": string
  }
}`;

  return {
    prompt,
    version: ACTION_04_PROMPT_VERSION,
    metadata: {
      action: 4,
      contract: "tx_2_imp_1",
      purpose: "Identify unreported and delayed team members from confirmation email content",
    },
  };
}
