// AUTO-GENERATED by AIVIC contract-module-scaffolder
// module: src/agents/tx-2-imp-1/prompts/action-04.ts

export const ACTION_04_PROMPT_VERSION = "1.0.0";

export interface Action04PromptInput {
  reportingDeadline: string;
  overdueThresholdHours: number;
  reminderContext: {
    totalEngineers: number;
    submittedCount: number;
    overdueCount: number;
    notSubmittedCount: number;
  };
  escalationRules: {
    maxReminderAttempts: number;
    reminderIntervalMinutes: number;
  };
}

export interface Action04PromptOutput {
  systemPrompt: string;
  userPrompt: string;
  version: string;
}

export function buildAction04Prompt(
  input: Action04PromptInput
): Action04PromptOutput {
  const systemPrompt = `You are an AI agent responsible for sending reminder notifications to engineers who have not submitted their daily reports.

Your role is to:
1. Identify engineers who have not submitted reports or submitted late
2. Determine which engineers should receive reminders based on escalation rules
3. Generate appropriate reminder messages
4. Track reminder attempts to prevent over-notification

Reporting deadline: ${input.reportingDeadline}
Overdue threshold: ${input.overdueThresholdHours} hours
Maximum reminder attempts per engineer: ${input.escalationRules.maxReminderAttempts}
Reminder interval: ${input.escalationRules.reminderIntervalMinutes} minutes

Current status:
- Total engineers: ${input.reminderContext.totalEngineers}
- Submitted: ${input.reminderContext.submittedCount}
- Overdue: ${input.reminderContext.overdueCount}
- Not submitted: ${input.reminderContext.notSubmittedCount}

Guidelines:
- Only send reminders to engineers who have not submitted or are overdue
- Respect the maximum reminder attempts limit
- Maintain a professional and supportive tone
- Log all reminder attempts with timestamps
- Escalate cases where engineers have received multiple reminders without response`;

  const userPrompt = `Based on the current reporting status and escalation rules, please:

1. Identify which engineers should receive reminder notifications
2. Determine the appropriate reminder message for each engineer
3. Check if any engineers have exceeded the maximum reminder attempts
4. Flag any cases that require human review or escalation

Current context:
- Reporting deadline: ${input.reportingDeadline}
- Engineers not submitted: ${input.reminderContext.notSubmittedCount}
- Engineers overdue: ${input.reminderContext.overdueCount}
- Maximum reminders allowed: ${input.escalationRules.maxReminderAttempts}

Please provide:
1. List of engineers to send reminders to
2. Recommended reminder message template
3. Any escalation flags for human review
4. Timestamp for reminder batch processing`;

  return {
    systemPrompt,
    userPrompt,
    version: ACTION_04_PROMPT_VERSION,
  };
}
